### ISSUE TITLE
delete button on user profile should ask for confirmation

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#100]
User's can delete their user account on the SlipStream server.  However, the button to do this should raise a confirmation dialog to ensure that the user realizes that this is an irreversible action.

**Comment by rbf** [comment]
This was implemented a while ago and is already in production:

![screen shot 2016-04-14 at 16 47 23](https://cloud.githubusercontent.com/assets/807084/14532248/b53fb3bc-0260-11e6-9f4d-60b57587f75b.png)


Closing issue.
