### ISSUE TITLE
add "run forever" options to "run..." dialog

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#104]
To allow users to change the default "run forever" options for a given deployment, these must appear on the "run..." dialog.  The defaults on the dialog should correspond to the values in the user's profile.

**Comment by mebster** [comment]
It should also be possible to set these in the image

**Comment by schaubl** [comment]
Linked to slipstream/SlipStreamUI#183

**Comment by rbf** [comment]
Outdated by #184, which in its turn is related to #183.

Closing.
