### ISSUE TITLE
add defaults values in "run..." dialog

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#105]
In the dialog for the "run...", if a given parameter has a default value, then the value for the default should appear in parentheses next to the parameter name.

**Comment by rbf** [comment]
This issue does not apply anymore because the default value is pre-filled in the `Run...` (now `Deploy...`) dialog:

![screen shot 2016-04-14 at 16 56 53](https://cloud.githubusercontent.com/assets/807084/14532627/03e4df64-0262-11e6-8837-b855568f377e.png)

Closing issue.
