### ISSUE TITLE
"run..." dialog for images should include an option for running (or not) the deployment scripts

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#106]
When running an image, the user may want to run the deployment scripts (in the case of a standalone image) or not (in the case of the running a raw image for tests).   An option for this should appear in the "run..." dialog for the image modules.

**Comment by mebster** [comment]
Why not making this the default? As long as we also require values for input parameters.

**Comment by schaubl** [comment]
Currently, the script is always executed.
This issue is probably outdated because it was created a long time ago when scripts wasn't executed for simple run.
@loomis do you agree ?

**Comment by loomis** [comment]
My recollection was that script are indeed always executed.  I have examples of this on the FranceGrilles SlipStream instance.  I think that this can be closed.

**Comment by mebster** [comment]
This feature is broken for images with input parameters. The Run... dialog should show input parameters without a default for the user to fill.  Otherwise, the execute script will block and timeout.

**Comment by loomis** [comment]
That's not the same issue as the one described in the title and comments.  See #199 instead.
