### ISSUE TITLE
Dashboard harmonisation

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#109]
In the Virtual Machines section:
- [ ] Rename column: SlipStream Id -> Run Id
- [ ] Shorten values
- [ ] Add tooltip with full value
- [ ] Do the same for Run Ids in Deployments / Runs / Builds section

**Comment by rbf** [comment]
This is not relevant anymore. The VMs table has been enhanced several times since, and currently in production it does look like follows:

![screen shot 2016-04-14 at 17 02 47](https://cloud.githubusercontent.com/assets/807084/14532880/eb6ee1f4-0262-11e6-924b-ac248f2cff79.png)

Closing issue.
