### ISSUE TITLE
Super should be able to change the status of a user directly

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#115]
E.g. NEW -> ACTIVE

**Comment by rbf** [comment]
@loomis Is this still valid?

**Comment by loomis** [comment]
@rbf No idea.  Don't even understand what the description means.

**Comment by mebster** [comment]
This is ancient. There was a time where user creation was moderated. The users we created un the NEW state and only once the moderator had accepted the new creation, the user was changed to ACTIVE.
