### ISSUE TITLE
Text fields for parameters in "Execute Deployment" dialog not responsive

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#139]
- Cursor keys don't work.
- Space is not taken into account (event where it makes sense).

Screenshot:

![slipstream_deployment_info_bug](https://cloud.githubusercontent.com/assets/807084/2944550/0ae19058-d9d5-11e3-99df-25e02fffb48e.png)

**Comment by schaubl** [comment]
Fixed in the new UI.
