### ISSUE TITLE
As Clara I can view "deleted" node instance, via an option

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#148]

**Comment by mebster** [comment]
Don't remember what this is about

**Comment by schaubl** [comment]
With the new UI all nodes instances are always displayed.
But previously only nodes instances that wasn't removed was displayed.
So this apply only with mutable Run when nodes are deleted.

**Comment by rbf** [comment]
Discussed with @loomis. This issue is outdated. Closing issue.
