### ISSUE TITLE
Can't change the category of parameters

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#152]
If a parameter has an Input category value, changing it to Output is ignored.

A workaround is to deleted the parameter -> save -> edit and add it back with the right category

**Comment by rbf** [comment]
@mebster 
The issue is still relevant, but it should be amended in the server side in order to take into account the change. The UI merely already allows it.

**Comment by rbf** [comment]
Closing since it's a duplicate of #278.
