### ISSUE TITLE
chooser misplaced when copying module with chrome on Windows

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#155]
The chooser window is misplaced (too large and cut off at right margin of window) when copying a module using the latest version of chrome on Windows.  This behavior is not seen on Mac/Chrome.

![bad-chooser](https://cloud.githubusercontent.com/assets/490506/4306235/4f12c396-3e7f-11e4-91ea-5b08a608cd59.png)

**Comment by mebster** [comment]
Is this still the case? @rbf

**Comment by schaubl** [comment]
no
