### ISSUE TITLE
copying module when using an invalid name causes a 500 error for users

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#156]
Copying an existing module to a new module with an invalid name displays a server error (500) to the user.  The underlying type of exception and message in the log file are correct: 
```
Caused by: com.sixsq.slipstream.exceptions.ValidationException: Invalid name, cannot contain space
```
but the user sees an server error with unhelpful error message instead.  This is reproduced on both Windows and Mac OS X.  The steps to reproduce this are:
  * Select a module to copy.
  * Click the "copy" button.
  * Select parent with the chooser.
  * Provide invalid new module name (e.g. "my new image" with spaces).

![copy-with-bad-module-name](https://cloud.githubusercontent.com/assets/490506/4306436/f540cf96-3e80-11e4-95a0-56de50453eae.png)

**Comment by rbf** [comment]
New UI (version > 2.4) fixes that with proper input validation in the name field:

![screen shot 2015-02-17 at 16 45 55](https://cloud.githubusercontent.com/assets/807084/6231062/90ce3514-b6c4-11e4-8047-bbfa89f1bf53.png)


Closing issue.
