### ISSUE TITLE
Having Virtual IP helpers would be good

### ISSUE THREAD

**Issue by yazun** [slipstream/SlipStreamUI#16]
Many (most) HA services rely on VIPs but there seems no standard to obtain one. It would be nice to have this functionality given by the orchestrator/api (ss-getvip) so it would be possible to uniformly build HA services on top of various providers.

**Comment by rbf** [comment]
@loomis @schaubl Any opinion about this issue? Is there a similar issue in another repo? Can we close it?

**Comment by schaubl** [comment]
@rbf: I don't think we have this issue somewhere else.
As far as I know we never hit this issue in our usecases.

**Comment by rbf** [comment]
Thanks. So closing the issue, since it's very old and does not seem to be relevant anymore.
