### ISSUE TITLE
launch button in AppStore tile isn't obviously a button

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#160]
A user was launching an application from the AppStore but instead of using the launch button on the time, clicked on the icon and then used the "Run..." button from the module page.  The user didn't realize that the launch button was an active element/button that would directly run the module.  The new UI should make this more visually clear (if it isn't the case already).

**Comment by rbf** [comment]
Adding this issue to `v2.6.0` since related to #220.

A cloud icon might make it more clear:

![screen shot 2015-03-30 at 16 07 03](https://cloud.githubusercontent.com/assets/807084/6897920/edcc2eae-d6f6-11e4-8db4-8a230c0e8abd.png)
