### ISSUE TITLE
Show user friendly state in dashboard (on error)

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#164]
The dashboard doesn't report errors when listing deployments. This is misleading.

**Comment by rbf** [comment]
@mebster 

This issue is flagged as urgent, but it's almost 2 months old.

What is precisely the issue? Highlighting the deployments that are in a failed state? Like for example:

![screen shot 2015-02-16 at 17 27 08](https://cloud.githubusercontent.com/assets/807084/6215504/94bcbeb6-b601-11e4-8503-93f87fe333ae.png)

As per the state machine for the runs found in [the Auto Scale documentation](https://github.com/slipstream/SlipStreamServer/wiki/Auto-Scale-Design), we could easily highlight in red runs in `Aborted` state, and in green runs in `Ready` state:

![state machine for runs](https://github.com/slipstream/SlipStreamServer/wiki/images/slipstream_new_state_machine_23.05.2014.png)

Would that go in the right direction?

**Comment by schaubl** [comment]
I think @mebster was think about the `abort` flag.

I think we don't need to highlight Runs in a final state (`Done`, `Aborted`, `Cancelled`).
But I like the idea to highlight with a **green** background deployment in `Ready`.
The **red** would be for deployment with the `abort` flag set and not in a final state.
I want to propose, for example, **blue** for deployment in a transitional state (except `Ready`).

**Comment by mebster** [comment]
Sounds good to me. We just need to add the ss:abort value to the run list.

**Comment by schaubl** [comment]
The ss:abort is already in the run list (in the XML) as an attribute named `abort`.

**Comment by rbf** [comment]
So in the metadata for the UI we already have both infos: `state` and `abort`. What is not clear to me is how the combination of those two values gives a certain other state of the run. Is it documented somewhere?

Using [the nice trend](https://github.com/slipstream/SlipStreamClient/issues/78) introduced by @schaubl :wink:, my question is, how is following tables completed?

| Run state    | `abort` flag set            |  `abort` flag NOT set        |
| --------------- | :---------------------------: | :--------------------------------: |
| `Initializing` | :wavy_dash:                | :blue_book:                      |
| `...`              | :wavy_dash:                | :blue_book:                      |
| `Ready`      | :closed_book:              | :green_book:                   |
| `Done`        |  :white_large_square:  |  :white_large_square:     |
| `Aborted`    |  :white_large_square:  |  :white_large_square:      |
| `...`             |  :white_large_square:  |  :white_large_square:      |

:white_large_square:: Nothing to highlight
:green_book::  Everything fine, highlight row in green
:closed_book:: Run has error, highlight row in red
:blue_book:: Run is in a transitional state, highlight row in blue
:wavy_dash:: Combination not expected

**Comment by schaubl** [comment]
I would replace the two :wavy_dash: by :closed_book: and use :closed_book: and :blue_book: for the `Finalizing` state

So the new table should be:

| Run state               | `abort` flag set            |  `abort` flag NOT set        |
| ------------------------ | :---------------------------: | :--------------------------------: |
| `Initializing`           | :closed_book:              | :blue_book:                      |
| `Provisioning`       | :closed_book:              | :blue_book:                      |
| `Executing`           | :closed_book:              | :blue_book:                      |
| `Sending reports` | :closed_book:              | :blue_book:                      |
| `Ready`                | :closed_book:              | :green_book:                   |
| `Finalizing`           | :closed_book:              | :blue_book:                      |
| `Done`                 |  :white_large_square:  |  :white_large_square:      |
| `Aborted`             |  :white_large_square:  |  :white_large_square:      |
| `Cancelled`          |  :white_large_square:  |  :white_large_square:      |

:white_large_square:: Nothing to highlight
:green_book::  Everything fine, highlight row in green
:closed_book:: Run has error, highlight row in red
:blue_book:: Run is in a transitional state, highlight row in blue

**Comment by rbf** [comment]
- [ ] The `ss:abort` popover doesn't show on the dashboard page (only in the `/run` page).

**Comment by schaubl** [comment]
I think the `ss:abort` popover should be shown when ss:abort is set, whatever the state of the Run but with a delay.

**Comment by rbf** [comment]
> I think the ss:abort popover should be shown when ss:abort is set, whatever the state of the Run

This is already the expected behaviour. Are you experiencing something different? 

> but with a delay.

We could do that. What does you suggest that?

**Comment by schaubl** [comment]
>> I think the ss:abort popover should be shown when ss:abort is set, whatever the state of the Run

> This is already the expected behaviour. Are you experiencing something different? 

I don't have the popover for Runs in state `Cancelled` and `Aborted`.


>> but with a delay.

> We could do that. What does you suggest that?

I'm suggesting that so that when we browse the list of Runs we are not bothered by popovers.

**Comment by rbf** [comment]
Ok. Moving back to `Working`. I'll have a look at those points.
Cheers.

**Comment by rbf** [comment]
- [x] **Fix:** I don't have the popover for Runs in state `Cancelled` and `Aborted`.
- [x] Add delay before displaying the popover with the `ss:abort` message,
