### ISSUE TITLE
Open points regarding the UI

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#166]
Please add here small or generic concerns regarding the ui.
# General
- [ ] Update README.md (compare with master first, since it has been updated, see 70d0ac5 and later).
- [ ] Review use of `media="screen,print"` for CSS files. See http://www.w3.org/TR/CSS2/media.html.
# Image
- [ ] Auto-detect script lang in ACE code editors for image edit mode
# JS Form sumbission
- [ ] Specify "accept type" to AJAX request.
  - [rbf] Waiting for the server to handle the reply as JSON correctly.
# User testing feedback
## From discussion with Lionel on Skype on 27nov2014, 16h30
- [ ] Welcome page scrolls to the bottom on page load (at least on Firefox)
- [ ] :warning: `Default cloud` not taken into account when saving the nodes in a deployment #691 
- [ ] Display a warning alert when a node has been flagged to be removed and still other nodes refer to one of its output.
- [ ] Prevent submitting the request to save a deployment if a node has been flagged to be removed and still other nodes refer to one of its output.
- ~~Remove head tag `<base hrel="/">` from prod and leave it only dev mode (to correctly find the css and js files on static)~~ => [rbf] the `base` tag is required to change the css path between `dev` and `prod` modes.
- ~~Ofuscate email address in `Contact us` menu action.~~
    => [rbf] unnecessary? Sources: http://stackoverflow.com/a/748805
                                  http://jasonpriem.org/2009/05/stop-obfuscating-email/
- [ ] :warning: Implement `Import` action: require an XML file of an image
- [ ] :warning: Add and implement an 'Export' button for images and deployments
## From discussion with Meb on Skype on Friday 28nov2014, 20h30
- [ ] Add a 3rd option to the type of input parameter mapping for global variables (`ss:state` and `ss:url.service`)
  => [rbf] Does it makes sense? Since they are already available in the deployment scripts, there is no point in mapping an input to them...
- [ ] When editing a deployment, check the nodes whose image reference is not a versioned one,
    and add if the input or output parameters changed, add the new ones and flag as removed the old ones (both visualy highlighted).
## From discussion with st at the office on Monday 01dec2014, 13h30
- [ ] Why for root projects we also ask: `Are group members inherited from parent module?`?
- [ ] Offer autocomplete for `Group members` input.
- [ ] AUTH checkboxes should be instead a ComboBox with 3 values: 'Owner', 'Group' and 'All'
- [ ] Live-update page header with new resource name (?)
- [ ] Version number **IS VERY WEIRD** ("I just did a new image, and it has the version 334?!") => [rbf] A name like `Version ID` would remove the user expectation that the version must increase by one on each save.
- [ ] Remove headers of summary section in general ('Name', 'Value')... they don't add any value.
- [ ] For a project with no children, default the "Image chooser" to the parent project instead of the project itself (because there are no children).
- [ ] Better explicit when node or image points to a versioned image.
## From discussion with Meb at the office on Wednesday 10dec2014, 14h00
- [ ] Remove JS client fixes for wrong request responses: save config, delete user, delete root module (update meb about it).
- [ ] Provide blank content messages for Welcome page (AppStore and Projects).
- [ ] Leave text hint on how to create sub-modules on project page.
- [ ] `Add Logo` action on top of the image-placeholder if no module logo defined...
- [ ] Enter GitHub issues for implicitely required fields, which the clients UI validates before sending requests.
- [ ] Service catalog: Test page with 50 times `my-cloud.1:local`.
## From discussion with Lionel on Skype on Friday 12dec2014, 13h00
- [ ] Check performance of Clj UI generation
- [ ] Check live if the bottom shadow of the iFrame in the 'Copy to' and 'Choose image' dialogs has to be shown
    => http://stackoverflow.com/a/22991952
- [ ] Do not ask for confirmation when leaving the an edit page if the user explicitely chooses "Cancel" action. (?)
## From discussion with Meb on Skype on Monday 15dec2014, 14h30
- ~~Truncate the list of nodes in the Run page to 10 to prevent overloading the page and the server.~~ => [rbf] we solved that by removing the performance critical features (i.e. JIT diagram and autorefresh) on large runs (i.e. >= 20 instances).
## From discussion with Cal at the office on Tuesday 16dec2014, 12h00
- [ ] Make logo image in App Store tile in the welcome page clickable. (?)
- [x] `Documentation` and `Contact Us` are in a weird place (i.e. inside the user menu)
    => [rbf] Agreed on 09jan2015 to place them in a new `Help` menu in the top bar
- [ ] In the chooser, if the user clicks in a link of a module for which she has no read
    access, an error page (404) is shown, and there is not visible way to go back.
- [ ] In a more general way, offer a visible way to navigate back in the chooser dialog.
- [ ] In a more general way, what to do with links to modules for which the user has no
    read access.
- [ ] The server doesn't honnor the 'chooser' flag for the error page. => [rbf] Still applies, at least when on the image chooser dialog, user navigates to an image for which the user has no the right view rights.
- [ ] Z-index problem with the gutter (side bar with line numbers): it goes on top
    of the secondary menu bar when scrolling.
- [x] 'X' Icon for error messages looks like if it was to close the alert.
- [ ] Make 'x' icon to close the alert more visible.
- [x] In the image chooser dialogs, inverse order of `Select` and `Select exact version` buttons (as it's now on prod, i.e. < v2.4).
## From discussion with Meb on Skype on Friday 19dec2014, 15h00
- [ ] Meb: Add `pagetype` string (for `view`, `edit`, `chooser` and `new` types)
    for `error` page, `configuration` page and `service catalog` page.
- [x] Meb: Verify that the run list in the dashboard include the `ss:abort` content beyond the run `state`
## From discussion with whole Team on Skype on Friday 9jan2015, 10h00
- [x] In user profile page, simplify description of default verbosity level, since the possible values are in the tooltip.
    => [rbf] Must be changed in the [Server](https://github.com/slipstream/SlipStreamServer/blob/a87f44557bcf2edd5d4f67a8e04c2798b1f74a2b/jar-connector/src/main/java/com/sixsq/slipstream/connector/ExecutionControlUserParametersFactory.java#L74) since the description is provided in the metadata XML.
- [x] Find a new icon for the nodes, since the current one looks like a checkbox.
- [ ] When scrolling a run page to the bottom, we don't see the state of the run.
- [x] In dashboard, sort runs and vms by date.
- [ ] :warning: `No connection` error for AJAX requests appearing often (esp. when saving config page)
- [ ] Consider changing the # url param for sections by a dedicated query param to avoid a bug in Firefox.
    => [rbf] Agreed to use the breadcrumbs for this.
- [ ] Display a spinner for syncronous actions like 'Terminate', 'Publish' before displaying the result alert.
- [ ] Unclear error message when creating a root project that has the same name than another project.
- [ ] While editing a deployment, nodes that are flagged to be removed are still taken into account to verify name-uniqueness of other nodes.
    => [rbf] Agreed to enhance header `div` for modules to reduce space waste:
       - Remove category from the title and move it to the subtitle
       - Add the module description as a separate suttitle line.
       - Add the category + version and commit message as a third line of the subtitle.
       - Reduce font and image sizes.
       - Include tooltip for icon.
## From discussion with whole Team on Skype on Friday 9jan2015, 10h00
- [x] Add a warning when clicking on an action, which is disabled because of the ACLs (like is currectly done for actions disabled for admin only)
# Other
- [ ] Check if the GET for the user profile resource is needed when refreshing the run page (or we can detect an error to the run request itself)
- [x] Detect inactivity to stop JS jobs (Suggested by Meb)
- [ ] Add the current username as a meta data in the HTML.
- [ ] Remove 'Save' button from the service catalog page for non super users.
- [ ] Add issue for the fact that a super can delete itself.
- [ ] Remove '/module/' from dashboard runs list.
- [ ] Fix Secondary menubar position on pageload when header is not visible.
- [ ] Move .js files that are specific to a view into `js/views`.
- [ ] Add validation to parameters
- [ ] Instance id by default in mapping?! => [nodename].[instanceid]:[outputparamname]
- [x] Remove 'default' from 'run deployment' dialog
- [ ] Add source to jQuery-Color in base.html:
    => https://github.com/jquery/jquery-color/
- [ ] Use a table-js-framwork to offer ~~pagination,~~ filter and ordering.
- [ ] In `model.js`, do not offer 'asImage()' for models other than images. ;)
- [ ] In `model.js`, remove .asImage() for images.
- [ ] Update dashboard runs and vms sections regularly.
- [x] Run Overview only renders correctly if the corresponding section is open at render time.
    => Reloading Run page with the overview section closed makes a wrong graphic
- ~~Enhance delete workflow to differentiate between deleting a version and an complete module.
    Ex: http://localhost:8080/module/examples/images/centos-6/105#cloud-configuration~~ => [rbf] The `delete` action always deletes the current displayed version. There is no way to "purge" all version of a module.
- ~~Do not require that a field has a value to validate it. Leave the regex check the specs.~~
- [ ] Add ALT+Enter to save/create. (?)
- [ ] :warning: Add a note about the fact that a module is not in the last version in the version summary line (apart from the alert).
- [x] :warning: When a module is not in the last version add a link to `Go to last version`.
- [ ] Add back icons into breadcrumbs (at least for `chooser`). (?)
- [ ] Fix new project when no query-param in url for category: E.g. `http://localhost:8080/module/someproj/new` => [rbf] The `new` page is displayed correctly, but the `Create` button doesn't work.
- [ ] The `CloudService` configured the node is not correctly displayed on deployment view (one randon cloud name one is displayed).
- [ ] Preselect the `userDefault` cloud in run deployment if node default cloud is `default`.
- [x] :no_entry: Tabs in Dashboard > VMS don't work because they have the same `#id` than the ones one section above.
- [x] The source module in the header of a Run page is not clickable.
    => [rbf] Instead of that, include the module in the breadcrumbs as mentionned above.
- [ ] If description and category of `deployment parameters` cannot be updated (this is currently the behaviour of the server), be coherent in the UI and do not make those editable other that for new parameters.
- [ ] Finish to remove dependency on BootstrapValidator because of the licence.
- [ ] Remove `<h1>` HTML tag from parameter `Email address for account approvals, etc.` in page Configuration, section SlipStream Support => [rbf] To be handled in the server: slipstream/SlipStreamServer#236

**Comment by mebster** [comment]
@rob: is this still relevant?

**Comment by rbf** [comment]
Yes. Some points are still to be fixed. We should review it and extract the relevant ones into issues.

**Comment by mebster** [comment]
Indeed.  You do that and close this old issue?
