### ISSUE TITLE
username is run header is not correct

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#167]
The run header has the text:
```
Deployment run started by 'super' 6 minutes and 13 seconds ago
```
to indicate who and when a run was started.  But the user given is the owner of the module rather than the user that started the run.  It should be the owner of the run rather than the owner of the module.

**Comment by rbf** [comment]
To make this more clear, both module owner and run owner are now included in the run page summary properly named and with corresponding help hints:

![run_vs_module_owners_02](https://cloud.githubusercontent.com/assets/807084/6105471/ab21a888-b057-11e4-9b66-947ac1abbd52.png)

If the logged user is the same (i.e. usernames are equal) than the run owner (i.e. the user who started the run), the subtitle is aware of that:

![run_vs_module_owners_01](https://cloud.githubusercontent.com/assets/807084/6105532/41e542c0-b058-11e4-8e4d-e0773df72974.png)

Note that if (and only if) the logged user has administrative rights (like in the first screenshot), usernames are clickable (this applies everywhere where a username appears).

@loomis 
Please close this issue if you agree with the changes.

**Comment by schaubl** [comment]
@rbf Username should be clickable if 
- the user has administrative rights
or
- the user is the user currently connected

**Comment by rbf** [comment]
@schaubl 
Makes sense, thanks.
See commit above.
