### ISSUE TITLE
Targets added through UI seem to have DOS line endings (cr)

### ISSUE THREAD

**Issue by yazun** [slipstream/SlipStreamUI#17]
Could be related to the browser (firefox, Mac OS) but deployment recipes have cr at the end of the lines.
This could be confusing for some of the commands..

**Comment by rbf** [comment]
I've just tested this and it is not the case anymore:

```
$ file /tmp/tmpv625lx
/tmp/tmpv625lx: Bourne-Again shell script text executable
$ # Remove shebang line from deployment script
$ file /tmp/tmpv625lx
/tmp/tmpv625lx_2: ASCII English text
```

So closing this issue.
