### ISSUE TITLE
Run page: If `ss:url.service` is not empty, a big link should appear on the header

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#170]

**Comment by rbf** [comment]
@schaubl Thanks for testing.

![screen shot 2015-02-13 at 14 52 46](https://cloud.githubusercontent.com/assets/807084/6188297/1b5f4bba-b390-11e4-9283-c93abf83b0be.png)

For reference, as mentioned in e9094d9a94fd955afa01c9f1db1bb9cf5318b2ed:

> I'd suggest this approach instead of the big link in the header we had
> in the previous version of the UI for the following reasons:
> 
>   - It's much less invasive code-wise (i.e. it can be done without
>     modifying a lot of code) from the current state of the code.
>   - It's more self-explanatory than the previous way of doing it.
>   - It's more consistent with the current UI since we re-use the alert
>     mechanism available accross the application.

**Comment by schaubl** [comment]
An improvement: slipstream/SlipStreamUI#200
