### ISSUE TITLE
Validate ssh key

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#172]
Common mistake in putting adding an ssh key is missing the leading format (e.g. ssh-rsa):

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIQLi3tUxTYQQL2gMabqUXsF89GuASJeIpZyDMjeUPDiJt9A83FV7QrMjQ4Dhg/3+k8rMO3VuAsqC3AAvn0URG3licNTO8DSyDKufGZGeSZeBu9iKg9hgRBkQ/pGc+flz/GfC8v2dalel+oGKagHwAjZNdECtnm8j066oPzhpEfYhrdj9lR8y6xGswCWRtF3XPLo9CaEeJZxV5AqzRBO4p/h2rVmkZ+Ruk3RfoAnrAhkTC8t8PgEx5qBlJ0O3m9jDZgmsmTEx7CAAgXtiVXVkhtHRw0TqvyjHY4uaxgWVUzlKydCWfkloBj3W0K5BmWTeBsKP5UcuSLCd1MnSznb0X

Validation should warn the user that the key is not valid. It should be possible to put an invalid key.

**Comment by rbf** [comment]
@mebster 

![screen shot 2015-02-12 at 17 05 49](https://cloud.githubusercontent.com/assets/807084/6173069/733bb676-b2e5-11e4-9208-82eb6c28add5.png)

Please validate and close the issue if you agree.

**Comment by mebster** [comment]
Looks good. What's the difference between the last two cases?

**Comment by rbf** [comment]
> What's the difference between the last two cases?

The reason to add the validation. 😉
(look at the beginning of the 3rd key).  


--
Robert Branchat
rob@sixsq.com
+41 22 575 2012

**Comment by mebster** [comment]
Ah. Got it. I thought the cross or check symbols corresponded to the line being validated. I was wrong. 

Ok, good.

**Comment by sixsq-hudson** [comment]
What do you check for in the first part of the key?

**Comment by schaubl** [comment]
sixsq-hudson was upgraded with an AI ?
Curently the regex is `^ssh-rsa \\S+(?: \\S.*)?[\n]*(?:[\n]ssh-rsa \\S+(?: \\S.*)?[\n]*)*$`.
But I already prepared this one: `^((([^ ]+ )?(ssh-(rsa|dss)|ecdsa-sha2-nistp(256|384|512)) [^ \n]+( .*)?)|(#.*))?(\n((([^ ]+ )?(ssh-(rsa|dss)|ecdsa-sha2-nistp(256|384|512)) [^ \n]+( .*)?)|(#.*))?)*$`

**Comment by loomis** [comment]
The validation should also accept an rsa1 key.  The protocol and format aren't recommended anymore, but there's probably someone out there who's still using it.

**Comment by rbf** [comment]
Note that the triggering use case for this validation was to help users to avoid entering invalid keys **unintentionally**, while leaving it open to enter anything if they like so. Therefore my approach is to start with a simple solution that correctly catches the case that makes up 80% of the usages, instead to try to come up with a formula that covers 100% of the cases. The message is only a warning inviting the user to double-check the value, without preventing the profile to be saved.

That being said, feel free to update the [regex used by this field](https://github.com/slipstream/SlipStreamUI/blob/master/clj/src/slipstream/ui/util/pattern.clj#L27-L30) to whatever to like to. :relaxed:

**Comment by schaubl** [comment]
The one that match version 1
`^((([^ ]+ )?((ssh-(rsa|dss)|ecdsa-sha2-nistp(256|384|512)) [^ \n]+|\d+ \d+ \d+)( .*)?)|(#.*))?(\n((([^ ]+ )?((ssh-(rsa|dss)|ecdsa-sha2-nistp(256|384|512)) [^ \n]+|\d+ \d+ \d+)( .*)?)|(#.*))?)*$`

**Comment by schaubl** [comment]
Done in aaa82475634ae58a819d5dfe262e49d35275334a
