### ISSUE TITLE
As a user, I should see coherent UI elements in the run page once the run is not active anymore.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#174]
When a deployment is in a terminal state<sup>1</sup> (i.e. because it failed, or because it was manually or automatically terminated), there are some UI elements that should be updated accordingly:
- [ ] The `Terminate` button should not be enabled anymore (currently the user might keep clicking it, wondering if the run is effectively terminated)
- [x] The info alert `The service is ready` must disappear. #200 

<sup>1</sup> Final states are [`cancelled`, `aborted` and `done`](https://github.com/slipstream/SlipStreamUI/blob/c2863d6a8bb9217b68ce241861fe89a9bdbee203/clj/resources/static_content/js/model.js#L235).

**Comment by schaubl** [comment]
The info alert `The service is ready` appear only in the `Ready` state.

**Comment by loomis** [comment]
Rescope to only the link.  We'll discuss the terminate button later.
