### ISSUE TITLE
Mutable deployment should allow to start nodes with zero multiplicity

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#177]
Now it's no longer possible due to max-provisioning-failures strictly required to be less than the multiplicity.  
When "Mutable deployment" check-box is checked, and the multiplicity is set to 0, max-provisioning-failures should just be a warning.

![screen shot 2015-02-20 at 14 29 29](https://cloud.githubusercontent.com/assets/353767/6286903/e2c8c2b8-b90c-11e4-9851-44bdc8e1379f.png)

**Comment by rbf** [comment]
So, detailed behaviour should be:

- For **non-mutable** deployments, the `Multiplicity` must be an integer `>= 1`, and an error should alert the user if not, preventing the run to be started.
- For **mutable** deployments, the `Multiplicity` must be an integer `>= 0`, and an error should alert the user if not, preventing the run to be started.
- In general, `Max provisioning failures` must be a positive integer strictly less than the `Multiplicity`, and an error should alert the user if not, preventing the run to be started.
- In general, if `Max provisioning failures` is a positive integer greater than the half of `Multiplicity` value a warning should alert the user but without preventing the run to be started.
- For **mutable** deployments, if the `Multiplicity` is set to `0`, the `Max provisioning failures` must be set to `0` as well.

@konstan 
Do you agree on that behaviour?
What is the priority of this bug?

**Comment by konstan** [comment]
Yes, agreed.
What is your scale? :) I'd say High (on "low, medium, high, critical" scale), because it broke formerly available feature, but there are not that many users out there using it.

**Comment by rbf** [comment]
Scale is "low, medium, high" as in:

![screen shot 2015-02-23 at 14 30 52](https://cloud.githubusercontent.com/assets/807084/6328521/a1ccc4b8-bb68-11e4-8ec5-2060d22e3f32.png)

:)

**Comment by sixsq-hudson** [comment]
Ok. Lets stick to High.

**Comment by rbf** [comment]
I'd suggest a more general solution: if the `Multiplicity` is `<= 1` we can directly disable the `Max provisioning failures` field, because no value other than 0 is valid in those cases.

1. what do you think of the solution?
2. by default, disabling a field, doesn't sent it with the ajax form. Does the server expect this field, i.e. will the request fail if the field `parameter--node--node1--max-provisioning-failures` is missing?

**Comment by konstan** [comment]
1. Agreed.
2. If this parameter is not part of the request form, it gets its default value which is 0.

**Comment by rbf** [comment]
Done:

![screen shot 2015-02-24 at 13 45 36](https://cloud.githubusercontent.com/assets/807084/6349694/42618aca-bc2d-11e4-874f-ae0d54348d0b.png)

NB: The screenshot on the left shows the `Non-mutable` case, and the right one the `Mutable` case. Note also the changes in the labels on the `Multiplicity` vs  `Initial multiplicity` fields.

@konstan 
Please validate once deployed, and close the issue if you agree.
Cheers.

Moving to `Ready to deploy`.
