### ISSUE TITLE
Editing deployment with the same name as a published image brings an notice message

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#178]
... or actually, this is because of editing the deployment where the node points to the published image with the same name?

In this case 
deployment: test-st/centos-6-25GB
published image: examples/images/centos-6-25GB

![screen shot 2015-02-16 at 18 47 14](https://cloud.githubusercontent.com/assets/353767/6288126/27ae2c88-b917-11e4-8897-c335bee4ae8a.png)

**Comment by rbf** [comment]
Not able to reproduce, at least at https://bb1.hnx.helix-nebula.eu/module/test-st/centos-6-25GB.

Anyway, the UI [drives this notification](https://github.com/slipstream/SlipStreamUI/blob/master/clj/src/slipstream/ui/views/module.clj#L49) (as well as the `Publish`/`Unpublish` secondary menu option for both [images](https://github.com/slipstream/SlipStreamUI/blob/master/clj/src/slipstream/ui/views/module/image.clj#L137-L138) and [deployments](https://github.com/slipstream/SlipStreamUI/blob/master/clj/src/slipstream/ui/views/module/deployment.clj#L56-L57)) by the metadata received from the SlipStreamServer, i.e. if a `publicationDate` attribute is present, the module is considered published (see [slipstream/ui/models/module.clj](https://github.com/slipstream/SlipStreamUI/blob/master/clj/src/slipstream/ui/models/module.clj#L77)).

I suggest to look at the `?media=xml` metadata, if you encounter this again and reopen this issue accordingly.

@konstan 
If you agree, please close this issue.

**Comment by konstan** [comment]
Yes, agreed.  Closing.
