### ISSUE TITLE
It wold be nice to have ss- command for  cloudbursting

### ISSUE THREAD

**Issue by yazun** [slipstream/SlipStreamUI#18]
Many components can report the load and if we want to scale-out, it would be nice to have possibility to spawn new instance/node of specific type. This would require special recipe field (or a flag during deployment) i.e. for the nodes joining the cluster (or leaving it after cloudbursting period is over)

**Comment by rbf** [comment]
Outdated.
Closing issue.

**Comment by schaubl** [comment]
With mutables Runs you can do what you want.
