### ISSUE TITLE
Remove 'default' from cloud choices and make it the option selected by default.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#180]
We might also prefix it in the label as `(your default)`.

**Comment by loomis** [comment]
I think that it is a good idea to mark which connector/cloud is currently the default; however, I'd prefer something less verbose like just adding an asterisk to the end.

**Comment by rbf** [comment]
Indeed. However it might not be clear for all users what the `*` means. 

![screen shot 2015-02-26 at 11 18 26](https://cloud.githubusercontent.com/assets/807084/6390087/a7fbeccc-bda9-11e4-8436-79e44f921f9c.png)

Same if placing it in front of the name:

![screen shot 2015-02-26 at 11 19 27](https://cloud.githubusercontent.com/assets/807084/6390094/b74642ae-bda9-11e4-9108-25d1ae2ceb16.png)

Explicit is better than implicit:

![screen shot 2015-02-26 at 11 18 52](https://cloud.githubusercontent.com/assets/807084/6390138/0b27df2c-bdaa-11e4-9560-96777c03d516.png)

Otherwise, a solution with the `*` would be to specify outside the combobox the meaning of the `*`. Something like:

![screen shot 2015-02-26 at 11 32 06](https://cloud.githubusercontent.com/assets/807084/6390281/2112e010-bdab-11e4-9cf7-acdf6f403462.png)

**Comment by loomis** [comment]
Personally, I prefer the asterisk as a suffix and putting the explanation in any help text accessible via a (?) button.

**Comment by rbf** [comment]
Was done with SlipStream/SlipStreamServer#200. Moving to `Validated` and closing.
