### ISSUE TITLE
In the 'Run deployment' dialog, add an option to the 'Global' section allow to define the clouds to be used for all nodes.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#181]
For deployments with only one node, we move the `Cloud` (or `Cloud credentials`) choice to the `Global` section of the `Run deployment` dialog, e.g.:

![screen shot 2015-02-25 at 16 58 48](https://cloud.githubusercontent.com/assets/807084/6374196/a9cd9784-bd0f-11e4-981e-3fa7baba8456.png)

For deployments with several nodes, the `Cloud` (or `Cloud credentials`) combobox for each node will not be shown, and instead, the `Global` section of the `Run deployment` dialog will have a global way to choose the cloud, e.g.:

![screen shot 2015-02-25 at 17 09 55](https://cloud.githubusercontent.com/assets/807084/6374482/7dfecb9e-bd11-11e4-9289-986a07ca3b5c.png)

The last option would reveal the current `Cloud` (or `Cloud credentials`) combobox for each node.

**Note:** if the deployment specifies different default clouds for each node, the global cloud combobox should directly have the option `Specify the cloud for each node` selected, and the corresponding comboboxes shown.

**Comment by rbf** [comment]
Current implementation pushed to branch [keep_running_in_run_dialog_#184](https://github.com/slipstream/SlipStreamUI/tree/keep_running_in_run_dialog_%23184):

![screen shot 2015-03-05 at 15 12 35](https://cloud.githubusercontent.com/assets/807084/6506772/b7612610-c34d-11e4-8204-ddc3ae807224.png)

**Comment by schaubl** [comment]
I found a bug with this feature: 
When a deployment has no node and we try to run it, the field `global-cloud-service` is sent with the request and the server return ```Error 409 - Conflict
Invalid key format: global-cloud-service
``` instead of ```Error: Deployment module provided for run is missing nodes. (409 - Conflict)```
Related to slipstream/SlipStreamServer#99

**Comment by rbf** [comment]
If the error returned by the server is not the expected one, is it not rather to be fixed in the server?

However, this seems to me like the wrong problem to fix. We have to have in mind following global UX goals to strive to:

  - Prevent as far as possible invalid user actions by make them very difficult (better: impossible) for the user to perform.

  - Promote actions that 80% of the users will probably want by making them very easy for the user to perform.

I.e. Unless there is a reason I forget, I'd completely prevent on the UI to save a deployment without nodes.

**Comment by schaubl** [comment]
Yes, the best thing to do is to prevent to run a deployment without nodes.

**Comment by schaubl** [comment]
And there is a check on the server side (just in case and for the API).
But we should ensure that the UI will not send any unknown parameter.

**Comment by rbf** [comment]
> But we should ensure that the UI will not send any unknown parameter.

1. What it the list of known parameters?
1. Why cannot unknown parameters simply be ignored by the server?
