### ISSUE TITLE
In the 'Run deployment' dialog, add an option to the 'Global' section to remind about the SSH key, making it optional.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#182]
E.g.:

![screen shot 2015-02-25 at 17 22 37](https://cloud.githubusercontent.com/assets/807084/6374771/58cbd13a-bd13-11e4-9f8d-9df135bec3a3.png)

Once the server doesn't fails if an SSH key is missing, an MVP of this feature can be quickly implemented as a simple reminder to the fact that the SSH key has to be defined in the user profile if the option is checked:

![screen shot 2015-02-25 at 17 23 28](https://cloud.githubusercontent.com/assets/807084/6374770/58c31752-bd13-11e4-884b-20f231df583b.png)

We can track if this option is indeed used a lot or not, and implement the fancy SSH generation mechanism if this is used a lot.

**Comment by mebster** [comment]
I think we need to do a bit more. If the user wants an ssh key, he/she needs to be able to add it in the Run... dialog, not requiring a round trip to the user profil. The 'Run deployment' button should only be enabled once we know we have a public key.

This key should also be available from the run itself.  This would allow users to assign different keys to different deployments. Something a feature that will be enhanced with the ability to manage credentials sets, which could include SSH keys.

**Comment by rbf** [comment]
> I think we need to do a bit more. If the user wants an ssh key, he/she needs to be able to add it in the Run... dialog, not requiring a round trip to the user profil.

I suggested this as a first step towards the functionality you mention, but which can be implemented very fast (half a morning) since it doesn't require any further changes. Then, if this is indeed used, we can spend more time allowing the user to directly to choose/add the SSH key(s) from here, in a similar way that we agreed to do with the cloud credentials. Or even offering the possibility to generate one SSH key pair directly from the SlipStream interface so that the user can download and install the private key.

> The 'Run deployment' button should only be enabled once we know we have a public key.

Only in the case that the user checks the suggested checkbox, right?
Or it is out of scope to allow launching a `Run` without an SSH key?

> This key should also be available from the run itself. This would allow users to assign different keys to different deployments. Something a feature that will be enhanced with the ability to manage credentials sets, which could include SSH keys.

I don't understand this part. Do you refer to the possibility to allow the user to directly to choose/add the SSH key(s) from here, in a similar way that we agreed to do with the cloud credentials.

**Comment by mebster** [comment]
> On 26 Feb 2015, at 16:06, rbf <notifications@github.com> wrote:
> 
> I think we need to do a bit more. If the user wants an ssh key, he/she needs to be able to add it in the Run... dialog, not requiring a round trip to the user profil.
> 
> I suggested this as a first step towards the functionality you mention, but which can be implemented very fast (half a morning) since it doesn't require any further changes. Then, if this is indeed used, we can spend more time allowing the user to directly to choose/add the SSH key(s) from here, in a similar way that we agreed to do with the cloud credentials. Or even offering the possibility to generate one SSH key pair directly from the SlipStream interface so that the user can download and install the private key.
> 
> 

Ok
> The 'Run deployment' button should only be enabled once we know we have a public key.
> 
> Only in the case that the user checks the suggested checkbox, right?
> 

Yes

> Or it is out of scope to allow launching a Run without an SSH key?
> 
> 

No it’s not out-of-scope.
> This key should also be available from the run itself. This would allow users to assign different keys to different deployments. Something a feature that will be enhanced with the ability to manage credentials sets, which could include SSH keys.
> 
> I don't understand this part. Do you refer to the possibility to allow the user to directly to choose/add the SSH key(s) from here, in a similar way that we agreed to do with the cloud credentials.
> 
> 

I mean from a run, being able to see the public SSH key used (if any) with this run.

The other part of this, is to use the Run… as an opportunity to explain to SSH aware Alices, that SlipStream will do all the necessary work required to deliver the public SSH key, independently of cloud specific SSH handling.

**Comment by rbf** [comment]
Got it, makes sense. Thanks.

**Comment by rbf** [comment]
Screenshot of current implementation state:

![screen shot 2015-03-05 at 16 18 00](https://cloud.githubusercontent.com/assets/807084/6507608/65721aca-c353-11e4-90a6-b6f583169f9b.png)

Corresponding help hint:

![screen shot 2015-03-05 at 16 23 14](https://cloud.githubusercontent.com/assets/807084/6507683/0778b022-c354-11e4-80ff-9f93376b59f1.png)


@schaubl 
We need to coordinate to move forward with this issue, since it's related to SlipStream/SlipStreamServer#250.

1. We need the user profile (or at least the SSH keys) to be included in the UI metadata
1. The checkbox value will be sent with the run `POST` request with the preliminary name `need-ssh-access`.

Cheers.

**Comment by schaubl** [comment]
@rbf : You have to remove the mandatory flag on the `SSH Public Key(s)` parameter of the user profile.
Because currently it's impossible to save the user profile if there is no SSH public key.

**Comment by schaubl** [comment]
@rbf : the state of the checkbox `need-ssh-access` is not included in the request.

**Comment by rbf** [comment]
@schaubl Working on it :)

**Comment by schaubl** [comment]
:+1:

**Comment by schaubl** [comment]
@rbf : Where are you with the issue I mentioned above ?

**Comment by rbf** [comment]
@schaubl I'm in front of my computer with the two issues. You will be notified when they are pushed. Cheers.

**Comment by schaubl** [comment]
Ok, thanks ;-)

**Comment by rbf** [comment]
> the state of the checkbox need-ssh-access is not included in the request.

Only the values of the `checked` checkboxes are included in form requests. You will be able to see the `need-ssh-access=on` in the `POST` request when it will be checked, i.e. when this story is finished.

**Comment by schaubl** [comment]
This is a problem because the default value is `on` so that when somebody uses the API, he will receive an error message if he didn't explicitly set `need-ssh-access` to `off`

**Comment by rbf** [comment]
This is the [default behaviour](http://stackoverflow.com/a/11424089) for forms. All other options in the the same form (and in the whole application for that matter) behave like this.

Some solutions are:

1. Handle a `input[type=hidden]`element which will be sent in any case.

1. Reformulate the option wording so that the result is the opposite: something like `I don't need SSH access` for the label and add `value=false` to the `input[type=checkbox]`, so that when the checkbox is `checked`, `false` will be sent.

1. Reverse the meaning of the flag on the server (not on the UI) so the default can be `false`, i.e. naming it something like `dont-need-ssh-access` or `decline-need-for-ssh-access`

For consistency with the standard behaviour with HTML forms, I'd go for 3. What do you think? Do you have another option?

**Comment by schaubl** [comment]
3 seems ok for me.
I would use `disable-ssh-check` or `disable-ssh-verification`.
But in this case we have to invert the meaning in the UI.

**Comment by rbf** [comment]
Mh, you are right: for 3. we have to reverse the meaning of the question on the UI. This is becoming to confusing.

A more straight forward approach would be to only look at the presence or not of the ssh key in the user profile, and:

1. if an ssh key is present (although unverified) add a hint saying that SSH access will be enabled:

![screen shot 2015-03-12 at 16 12 50](https://cloud.githubusercontent.com/assets/807084/6620834/3f9ffefe-c8d3-11e4-9e7a-62c6c9a4ee90.png)


2. if the ssh key field is empty, add a hint to let the user know how to fix it:


![screen shot 2015-03-12 at 16 12 07](https://cloud.githubusercontent.com/assets/807084/6620841/4c34b560-c8d3-11e4-877c-c71a2ec5f0d3.png)

(We can also display a disabled checkbox instead of textual labels)

Doig so, there is no option that the server has to check for: if there is an SSH key, the server installs it, and if no, it doesn't.

Thoughts?

**Comment by schaubl** [comment]
Ok for me but since I already implemented the check based on the parameter `need-ssh-access` of the request, we can keep it and add a hidden field to the UI which will always set this value to `false`.

And in this case I would like to change the parameter name to `disable-ssh-check` or `disable-ssh-verification` which songs better (at least for a user of the API).
So the UI will have to add this parameter as a hidden field with the value `true`.

**Comment by rbf** [comment]
I agree: since the flag is already implemented we can leave it there so that it can be used via the API, and maybe we find it useful to leverage it also on the UI.

I agree also to reverse the flag meaning. Since `disable-ssh-check=true` might be misleading, what about a positive wording like `bypass-ssh-check` or `ignore-missing-ssh-key` ?

**Comment by schaubl** [comment]
Ok, tell me the one you prefer.

**Comment by rbf** [comment]
:smiley: You tell me: it's more important for the consistency of the server code.

**Comment by schaubl** [comment]
let's take `bypass-ssh-check`

**Comment by rbf** [comment]
:+1:

**Comment by rbf** [comment]
BWT, the param `bypass-ssh-check` should also be included in the forms to launch `Run Image`? And (doesn't sound logical to me but) `Build Image`?

**Comment by schaubl** [comment]
Yes for the `run image`.

For `build image` the user key is not used so the check should not complains. 
I will check that this behaviour is correctly handled.

**Comment by rbf** [comment]
:+1: I'll add them to both `run` and `build` dialogs in that case (they are generated from the same HTML template).

**Comment by schaubl** [comment]
@rbf : I just checked and the behaviour is respected, so no need to add `bypass-ssh-check` for `build image`.

**Comment by rbf** [comment]
But can I anyway include it, since they are generated from the same HTML template?

**Comment by schaubl** [comment]
Yes, you can. 

The check is the following:
```java
if (type != RunType.Machine && !bypassSshCheck) {
    RunFactory.validateUserPublicSshKeys(user);
}
```

**Comment by rbf** [comment]
:+1: Cheers.

**Comment by schaubl** [comment]
Demo done

**Comment by rbf** [comment]
Changes pushed to `keep_running_in_run_dialog_#184`. Moving to `Done`.
