### ISSUE TITLE
In the 'General' section of the 'User profile', refactor both 'keep execution running' checkboxes into a 4-item combobox.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#183]
E.g.:

![screen shot 2015-02-25 at 17 48 03](https://cloud.githubusercontent.com/assets/807084/6375593/53525152-bd18-11e4-9640-4f49ed4be525.png)

This parameter should be accompanied by a detailed help-hint (especially to explain why one would like to leave a deployment running it it fails, and terminate it if it succeeded).

To makes things consistent, the server should be updated to accept the value selected in this new combobox. If that's not doable now, the UI will hide the current checkboxes and update them according to the combobox selection.

## Downstream dependencies:

- [ ] Include the combobox in the `Run deployment` dialog to choose the one-time behaviour for that run, #184 
- [ ] Include the combobox in the `Deployment` page to choose the suggested default behaviour, #193

**Comment by mebster** [comment]
The following precedence should exists:
1. profile (default)
2. deployment
3. run...

**Comment by rbf** [comment]
As [suggested](https://github.com/slipstream/SlipStreamUI/issues/184#issuecomment-76028582) by @loomis:

![screen shot 2015-03-01 at 23 18 11](https://cloud.githubusercontent.com/assets/807084/6433220/5fc4173c-c069-11e4-9e02-889873793d95.png)

The hint would be either as displayed or hidden in a popover on a `?` icon following the standard of the rest of the page.

Related to #184.

**Comment by rbf** [comment]
This was done as side-effect from SlipStream/SlipStreamServer#255, without need of changes in the UI. Closing issue and moving to `Validated`.
