### ISSUE TITLE
In the 'Global' section of the 'Run deployment' dialog, add the combobox to choose the 'keep execution running' behaviour for that run.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#184]
E.g.:

![screen shot 2015-02-25 at 18 06 04](https://cloud.githubusercontent.com/assets/807084/6375683/017322e8-bd19-11e4-8e18-be8482de7244.png)

The server will need to include in the metadata of the deployment page, which behaviour the user selected as default in the user profile, so that it can be preselected in the `Run deployment` dialog.

**Comment by schaubl** [comment]
This is part of the user profile which is included in the metadata.

**Comment by loomis** [comment]
An alternative for the question/answer which has shorter alternatives:
"Terminate application after deployment": "always", "on success", "on error", "never".

**Comment by rbf** [comment]
As suggested by @loomis:

![screen shot 2015-03-01 at 23 18 11](https://cloud.githubusercontent.com/assets/807084/6433220/5fc4173c-c069-11e4-9e02-889873793d95.png)

The hint would be either as displayed or hidden in a popover on a `?` icon following the standard of the rest of the page.

Related to #183.

**Comment by rbf** [comment]
@schaubl

FYI regarding SlipStream/SlipStreamServer#255, I'm naming the form field `keep-running`, and its values `always`, `on-success`, `on-error` and `never`:

``` html
<select name="keep-running" id="keep-running" class="form-control">
  <option selected="" value="always">Always</option>
  <option value="on-success">On Success</option>
  <option value="on-error">On Error</option>
  <option value="never">Never</option>
</select>
```

Please let me know if we have to find a better naming.

**Comment by loomis** [comment]
Use consistently "Always", ..., "Never" for all of the comboboxes (user and run pages).

**Comment by loomis** [comment]
The default value in the combobox should be the value set in the user's profile.

**Comment by rbf** [comment]
Pending tasks after the demo (from the comments above):

- [ ] Use consistently "Always", ..., "Never" for all of the comboboxes (user and run pages).
- [ ] The default value in the combobox should be the value set in the user's profile.

**Comment by schaubl** [comment]
- [ ] Mutable run should be set to Always.

**Comment by schaubl** [comment]
The description of the keep running combobox is wrong (it's the opposite).
- [ ] Change it to `Keep the application running after deployment`.
- [ ] Change it's instructions accordingly.

**Comment by rbf** [comment]
After demo, I'll add following two points, to match the cloud setting:

- [ ] Flag with an `*` the default `keepRunning` setting
- [ ] Document the meaning of `* ` in the help hint

**Comment by schaubl** [comment]
Demo done

**Comment by rbf** [comment]
Changes pushed to branch `keep_running_in_run_dialog_#184`. Moving to `Done`.
