### ISSUE TITLE
in the dashboard, move tags to beginning of run display table

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#185]

**Comment by rbf** [comment]
@loomis 
Do you mean to turn the run table into this?

![screen shot 2015-03-01 at 22 53 05](https://cloud.githubusercontent.com/assets/807084/6433089/ebeb61c4-c065-11e4-803d-e137e9222442.png)

The `Tags` column can contain a different number of tags resulting in unpredictable column size. Making a weird and random layout.

Maybe we can find a better solution if we understand the rational of the change.

**Comment by loomis** [comment]
Yes, that was my intention: getting the user supplied information up front.  I think it is unlikely that the user is going to set many tags on a run.

**Comment by rbf** [comment]
Discussed with @loomis. This issue is outdated. Closing issue.
