### ISSUE TITLE
in dashboard, provide global run list

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#187]
Change from tabs with a "by cloud" view of the runs to a single table with all of the runs for all clouds.  The entries should be by default ordered with the most recent runs first.  

The table should allow selection by value for enum columns (e.g. state, cloud) and ordering (ascending, descending) for other values.

**Comment by mebster** [comment]
There are many features mixed in this issue. Filter and sorting on tables with or without backend roundtrip is a bigger feature than simply adding a new default tab 'all'.

**Comment by rbf** [comment]
I created a higher level issue to discuss on the redesign of the `Dashboard` page, and I'm moving this one to `Backlog` for the time being.

**Comment by schaubl** [comment]
See #252.
@loomis if you agree with the 252, we can close this issue.

**Comment by rbf** [comment]
IMO we need to do a proper workshop to redesign the Dashboard (see #206) like we did for the run page, instead of doing tactical changes on-the-fly like this.

**Comment by schaubl** [comment]
@rbf: I agree that we have to do this "workshop" but I think we can still do some "on-the-fly" changes because they changes are simple and can improve a lot the user experience.

@loomis: So can we close this issue ?

**Comment by loomis** [comment]
Sure.
