### ISSUE TITLE
remove view of individual VMs from dashboard

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#188]
To more emphasize that SlipStream deploys applications rather than VMs, remove the section with individual VMs from the dashboard.

This information should instead be provided via a modal panel that is activated when the user clicks on a "details" link for a given run.

**Comment by mebster** [comment]
I think this is too radical.  I would rather move the metrics section next to the usage and make the usage section more apps focused. The the current VMs section is last and lest important.

**Comment by rbf** [comment]
IMO these sudden change suggestions related to the Dashboard page (also #187) are still a bit out of context. We should sit down and thoughtfully re-design the Dashboard page, in the same productive way that we did yesterday to focus on streamline, speed-up and enhance the user onboarding experience.

**Comment by rbf** [comment]
Discussed with @loomis. This issue is outdated. Closing issue.
