### ISSUE TITLE
add "first time user welcome" page to registration workflow

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#191]
After the users have set their initial passwords, they should be redirected to a "first time user welcome page".  This page should invite the user to follow an "alice" or "clara" tutorial (or just skip to using SlipStream).  The links should activate the appropriate tutorial.  Initially this could just be a landing page with information about existing documentation resources.

**Comment by mebster** [comment]
The landing page could be in SlipStream or on HubSpot from the sixsq.com website.

**Comment by loomis** [comment]
If it is outside of SlipStream it needs to be configurable to avoid breaking the registration workflow for the community edition.

**Comment by schaubl** [comment]
I think it should not be outside SlipStream.
My personal view of this feature is a overlay on the home page of SlipStream with 2 big choices of tutorials (plus a smaller button to ignore). Then when you click on a tutorial the overlay disappear and you are at the right place (home page) to start being guided.

**Comment by mebster** [comment]
A guided tour is definitely best. And having it configurable is a good idea, such that it can be overloaded if needed. The question is if we can do it incrementally or not.

**Comment by rbf** [comment]
Upstream dependency: #197 Create a tour for Alice.

Anyway, the Alice tour is the max common denominator for the features that any user should be guided through. Therefore I'd first prepare this first Alice tour showing it to all new users by default (always being able to opt-out) and afterwards add this "first time user welcome" page prepared when we have a second  tour prepared.

**Comment by rbf** [comment]
This issue is somehow outdated since now the tour dialog always appears after login until the user dismisses it (see screenshots below). Flagging it as `✖︎ Outdated - Flagged for deletion` for discussion.

![screen shot 2016-04-14 at 17 28 35](https://cloud.githubusercontent.com/assets/807084/14533690/5e07f2f2-0266-11e6-8941-13b5bda8212e.png)

**Comment by rbf** [comment]
Discussed with @loomis. This issue is outdated. Closing issue.
