### ISSUE TITLE
refactor cloud choice combobox in run dialog to a credential choice

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#192]
The cloud choice combobox in the run dialog should be refactored to allow a choice of credentials instead.  In the short term, this would be the list of clouds for which the user has provided credentials.  

There would also always be an option to "Add credential...".  This option would bring up a modal dialog box which would:
- Ask which cloud to use
- An optional name which defaults to the cloud name
- Cloud specific parameters with help for each.
- An explanation on how to get credentials for that cloud.
  The modal dialog should either automatically verify the credentials or provide a button to manually check them.

**Comment by rbf** [comment]
Example of similar workflow for credit cards form Udemy.com:

![screen shot 2015-03-02 at 06 13 59](https://cloud.githubusercontent.com/assets/807084/6435695/849c7b14-c0a3-11e4-897b-f76cec1d4d0e.png)

**Comment by mebster** [comment]
Only support adding/modifying the credentials corresponding to the cloud. Do this as a son put. Need to ensure son put is supported.

**Comment by schaubl** [comment]
Fix slipstream/SlipStreamServer#200.
