### ISSUE TITLE
In the 'Global' section of the 'Module' page, add the combobox to choose the default 'keep execution running' behaviour for that deployment.

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#193]
The same "keep running..." combobox option should be added as a global deployment parameter, allowing the application creator to decide what the default behavior should be.  An additional option for the deployment would be to use the user profile default value.

**Comment by rbf** [comment]
A `Global` section doesn't yet exists for a deployment, unless we refer to the `Summary` section.

**Comment by rbf** [comment]
See #183 (linked above) for details on the design of the combobox.
