### ISSUE TITLE
As an application developer, I can provide deployment notes for an application that will be shown to the user before deploying it, in order to clarify expectations or technical requirements of the application deployment.

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#195]
Add a text field that allows the application developer to provide information about the application requirements that may need to be set outside of SlipStream.  For example, the port 80 must be open in the default security group to allow a web service to be properly deployed in AWS.   This is a short term solution to our current poor handling of security groups.

**Comment by rbf** [comment]
This is a short-term solution for the security groups handling but will have sense anyway after that is properly fixed. In that sense, I would name this field rather `Deployment notes` to highlight the fact that the field can be used to explain other points like:
- which actions the user should take to properly allow the deployment to succeed,
- what is the expected result of the deployment,
- how long it's normally expected to take,
- if, how and why it supports mutable deployments.

**Comment by schaubl** [comment]
@mebster decided to do this task during this Sprint.

**Comment by schaubl** [comment]
@mebster : here is the task for `notes` in the UI.

**Comment by rbf** [comment]
As I understand from the corresponding change server side (slipstream/SlipStreamServer#252) `note`s are stored at image level:https://github.com/slipstream/SlipStreamServer/pull/291/files

@loomis @schaubl 
How must the `PUT` request to the server look like to add or update an image node? Simple adding a field named `note` to the request?

Thanks.

**Comment by mebster** [comment]
Yes simply add an 'note' element (in xml) or a form input element named 'note'. See https://github.com/slipstream/SlipStreamServer/pull/458 for details.

**Comment by schaubl** [comment]
I added one more star to this task and promoted it to `Proposed for Sprint` because AFAIK it has been implemented server-side a while ago and we "only" need to update the view in the UI to benefit from this feature.
