### ISSUE TITLE
Mutable actions should be available from the UI

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#198]
Such that Alice can up/down a mutable deployment

**Comment by rbf** [comment]
This is not a trivial one. There are lots of ways to implement that, and the controls can be placed in several places:

![screen shot 2015-02-26 at 16 30 20](https://cloud.githubusercontent.com/assets/807084/6394923/2e1e6a16-bdd5-11e4-9015-dacca21dcdb1.png)

Also, is the user able to do only `+/-1` (add one instance and remove only one given instance at a time), or the `multiplicity` value can be freely edited, for example (giving SlipSteam rules for the instances to be terminated, i.e. `terminate oldest instances`)?

**Comment by schaubl** [comment]
On mutable Runs, you can:
- Add x new node instances for one node. (x > 0).
- Remove specific node instances of one node. (nodes instances specified by a comma separated list of ids)

So the `add node instances` feature should be added on the level of the node with a question that asks `how many ?`
and the `remove node instances` feature should be added either on the node and propose a list where you can select the one you want to add or either on each node instances.

**Comment by mebster** [comment]
Adding new node is simpler (once we've decided where to put the single button).
Removing instances, is trickier, as we need to be able to select a bunch of instances and mark them for removal. And then trigger the remove action.

The difficulty in adding the add button might point to the need to re-design in part the page. This will require another UI design session.

**Comment by rbf** [comment]
This issue is not yet ready for the current sprint, since we need to discuss how to implement that.

**Comment by rbf** [comment]
IMO this point is today still relevant. Promoting to `Top of Backlog`.
