### ISSUE TITLE
Failure of any of nodes reported is cryptic

### ISSUE THREAD

**Issue by yazun** [slipstream/SlipStreamUI#2]
When a node fails, orchestrator says sth like 
ss:abort	Failed to connect to 185.12.7.254: Failed to connect after 600 sec.

which with number of nodes means manual analysis of all the logs of all the nodes.
The error should at least indicate originating machine. Also all nodes go to 'red' as their scripts are aborted which does not help to trace the problem.

**Comment by rbf** [comment]
Discussed with @loomis. This issue is outdated (see https://github.com/slipstream/SlipStreamServer/issues/601). Closing issue.
