### ISSUE TITLE
As a user, I can set up deployment tags directly in the 'Run deployment' dialog, in order to flag and name the deployment.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#209]
This is a more flexible way to allow the user to name a deployment.

Related to #196.

**Comment by mebster** [comment]
Only support comma separated strings, without spaces.

**Comment by schaubl** [comment]
I think currently space are not supported.
I wanted to propose to allow spaces.
It can be better if we display tags as `Labels` http://getbootstrap.com/components/#labels

**Comment by rbf** [comment]
Or maybe better than labels, we could try later on with a token field (although spaces are not supported by default):

http://sliptree.github.io/bootstrap-tokenfield/

![screen shot 2015-03-02 at 14 43 22](https://cloud.githubusercontent.com/assets/807084/6441685/85d873ba-c0ea-11e4-99e5-b3e67da1df9e.png)

**Comment by rbf** [comment]
Screenshot of the result of the commit above:

![screen shot 2015-03-05 at 17 55 42](https://cloud.githubusercontent.com/assets/807084/6509626/e5145d4e-c360-11e4-9732-d7f4523292eb.png)

@schaubl 

FYI for SlipStream/SlipStreamServer#251, I've pushed this change above to the [`keep_running_in_run_dialog_#184`](https://github.com/slipstream/SlipStreamUI/tree/keep_running_in_run_dialog_%23184) branch. The tags are included in the run `POST` request with the name `tags`, the same as in the `run` page.

**Comment by schaubl** [comment]
@rbf : Yes, `token fields` is exactly what I was thinking when I spoke about `labels`

**Comment by rbf** [comment]
Created #224 for that.

**Comment by rbf** [comment]
@schaubl

As mentioned above:

> The tags are included in the run `POST` request with the name `tags`, the same as in the `run` page.

Do you need a different parameter name that better fits into the form format?

**Comment by schaubl** [comment]
> Do you need a different parameter name that better fits into the form format?

@rbf : no, tags is ok.

**Comment by rbf** [comment]
:+1:

**Comment by schaubl** [comment]
@rbf : I implemented this feature server side but tags are sent surrounded by simple quotes.
Example: 'Titi, Toto'
