### ISSUE TITLE
Remove gradients for 'pressed' effect of menus in top bar.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#210]
As suggested by @mebster, following gradient should be removed, at least for the blue theme:

![screen shot 2015-03-02 at 08 33 41](https://cloud.githubusercontent.com/assets/807084/6436886/e8982cfe-c0b6-11e4-8b43-321aa3cec990.png)

![screen shot 2015-03-02 at 08 30 30](https://cloud.githubusercontent.com/assets/807084/6436874/ac336972-c0b6-11e4-8825-563039670a40.png)

**Comment by schaubl** [comment]
At the same time, maybe the color of the text in the submenu of the blue theme can be changed.
I don't really like the black on top of light blue.
Maybe dark blue will be better.

**Comment by rbf** [comment]
Sure, I'll try a couple of variants when I'll work on that.

**Comment by rbf** [comment]
@mebster 
I miss a bit the _pressed_ effet but it looks cleaner indeed:

![screen shot 2015-03-06 at 18 47 58](https://cloud.githubusercontent.com/assets/807084/6530464/69de2a70-c431-11e4-9852-d3777f364ba9.png)

![screen shot 2015-03-06 at 18 46 07](https://cloud.githubusercontent.com/assets/807084/6530475/82fbe524-c431-11e4-849c-3fcf9e23d4d5.png)

Pushed to [`keep_running_in_run_dialog_#184`](https://github.com/slipstream/SlipStreamUI/tree/keep_running_in_run_dialog_%23184) branch.


@schaubl 
The foreground color was already not black but a [very dark blue](https://github.com/slipstream/SlipStreamUI/blob/ca621a8a188db6d9cd8d773fa47d06e91aa80c71/clj/resources/static_content/themes/helixnebula/css/custom.css#L19). :wink: Now reusing the same dark blue as in the breadcrumbs bar background:

![screen shot 2015-03-06 at 18 56 33](https://cloud.githubusercontent.com/assets/807084/6530631/c44036c4-c432-11e4-8e88-f1d636a20ad7.png)

What about that?

**Comment by rbf** [comment]
HNX instance still has to be updated in order to have this fix.
