### ISSUE TITLE
Add a link to the last version if not in the last version of a module.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#212]
The current info if the user views a module in an outdated version is this:

![screen shot 2015-03-02 at 08 51 44](https://cloud.githubusercontent.com/assets/807084/6438704/ff601914-c0cb-11e4-8402-84e0271f2b9b.png)

We could easily add here a link to the last version, e.g. 

![screen shot 2015-03-02 at 08 51 36](https://cloud.githubusercontent.com/assets/807084/6438715/15e1a522-c0cc-11e4-9415-afe1abae4fd2.png)

**Comment by schaubl** [comment]
:+1:

**Comment by loomis** [comment]
Add a delay before showing help text associated with the link (help in summary section, opens that section).
