### ISSUE TITLE
Alerts accumulating with same message repeated

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamUI#217]
On the Run page the messages (both 'The service is ready' information and 'Error') are added after each refresh.
![screen shot 2015-03-03 at 10 35 18](https://cloud.githubusercontent.com/assets/16004/6462373/d3dea318-c1a8-11e4-828e-8baa61ccbcc0.png)

**Comment by schaubl** [comment]
This has been fixed here: #203

**Comment by rbf** [comment]
You got me, but it's a [feature](http://www.footmercato.net/images/a/ca-plane-pour-le-barca_103704.jpg).

**Comment by schaubl** [comment]
I updated the Saas. Now it should work.
