### ISSUE TITLE
Wrong 'version comment' shown in the header and in the summary section

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#218]
If I have a deployment with one node linked to one image.
And if this deployment has not 'version comment' but the image has one.
The deployment will show the 'version comment' of the image.

**Comment by rbf** [comment]
Accepted for v2.6.0. Easy to fix.

**Comment by schaubl** [comment]
Looks like this task was removed from the Sprint v2.6.0, so I'm removing the milestone.
