### ISSUE TITLE
Support chat window shouldn't be shown on the chooser popups

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#222]
See "Let's talk!" popup window bars in both main and the chooser popup windows.

![screen shot 2015-03-10 at 11 28 30](https://cloud.githubusercontent.com/assets/353767/6573273/9d988500-c719-11e4-8f07-f88ff4eb5d00.png)

**Comment by mebster** [comment]
Oops. Need to test that we're not in a iframe

**Comment by rbf** [comment]
1. Do we want to remove it from the chooser? (IMO yes)
1. Is it urgent? (IMO yes and fix in one-liner on UI side, i.e. do not include support.js on chooser)

If do not shout agains both points above, I'll fix it now.
Cheers.

**Comment by schaubl** [comment]
1. Yes
2. Yes

**Comment by schaubl** [comment]
The `Let's talk` box should not appear automatically and should be on the right.

**Comment by konstan** [comment]
I just saw it on Reports tab as well.

**Comment by rbf** [comment]
Same issue. Will be fixed with the same fix.

**Comment by rbf** [comment]
Fixed with the issue above, and pushed to master.
Please validate and close the issue when done.
Cheers.

**Comment by rbf** [comment]
HNX instance still has to be updated in order to have this fix.
