### ISSUE TITLE
The code editor content goes in front of the secondary menu bar when scrolling

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#225]
![ui-code-editor-bug](https://cloud.githubusercontent.com/assets/2462866/6604051/1a7d061a-c826-11e4-8d28-05af72fc0f26.png)
This is probably due to a issue with `z-index`.

**Comment by rbf** [comment]
This issue is tracked in the catchall issue #166:

> Z-index problem with the gutter (side bar with line numbers): it goes on top of the secondary menu bar when scrolling.

On Friday I will review these open points and convert into proper issues the ones that are still relevant.

**Comment by loomis** [comment]
Verify or close.

**Comment by schaubl** [comment]
Also check the behaviour of the height of the code editor.
Sometime the height is higher than any screen but we still have some scrollbar inside the code editor.

**Comment by schaubl** [comment]
The issue seems to be fixed
