### ISSUE TITLE
When login with the mobile version, error message are not visible

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#226]
The error message is not visible because the login "overlay" is on top of the error message.
![ui-mobile-login-error](https://cloud.githubusercontent.com/assets/2462866/6604490/f726173a-c828-11e4-9d3f-851ba6d6c06c.png)

**Comment by rbf** [comment]
For reference, now a small alert fades in for 2 secs on top of the "login" button, displayed like this:

![ios simulator screen shot 22 jul 2015 18 59 46](https://cloud.githubusercontent.com/assets/807084/8831889/ad9b3efc-30a5-11e5-8d6a-5db371a74058.png)


The previous alert is still present, in case the user closes the menu.
