### ISSUE TITLE
Improve Run&Build image dialog to allow only Clouds where the image can be build/run

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#227]
For a run image: If the image has to be build, is it build ?
For a build image: If the image is not yet build ?
For both: Does the user has Credentials for this Cloud ?
![ui-run-dialog-improvement](https://cloud.githubusercontent.com/assets/2462866/6604936/67d1682e-c82c-11e4-852e-0936d40747ab.png)
![ui-build-dialog-improvement](https://cloud.githubusercontent.com/assets/2462866/6604938/6adafd28-c82c-11e4-8ee2-5df352208183.png)

**Comment by rbf** [comment]
:+1: 

Are these infos available on the metadata provided to the UI for the `image` page?

**Comment by schaubl** [comment]
> Are these infos available on the metadata provided to the UI for the image page?

If it's an image that has to be build (one of recipe, pre-recipe, package defined), yes.
For Cloud credentials, yes.
But if you want to run an image which is just a link to an other image, no (or not yet) because we need the full images hierarchy.

**Comment by mebster** [comment]
We should process that info before giving the data to the UI. New attribute canRun? And the same for canBuild?

**Comment by schaubl** [comment]
Related to #79.

**Comment by schaubl** [comment]
A new feature was just implemented in slipstream/SlipStreamServer#267 and slipstream/SlipStreamClient#83
This feature allow to Run an image which wasn't built.

So there is no need to implement the `Simple Run` part of this issue.

Only the check for `Already built` on `Build` is needed and all informations are there.
So I'm adding 2 stars.

@mebster and/or @loomis can you consider this issue for the next sprint ?
