### ISSUE TITLE
Long connector names don't wrap around well

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#228]
![screen shot 2015-03-16 at 09 26 49](https://cloud.githubusercontent.com/assets/419519/6663464/c253713a-cbbe-11e4-804d-c67f1a474446.png)

**Comment by rbf** [comment]
Done.

Screenshot of the example in the [HTML template](https://github.com/slipstream/SlipStreamUI/blob/c2e734070f49ea0f864013ae5750cd3693c1be05/clj/src/slipstream/ui/views/html/subsection.html#L99):

![screen shot 2015-03-30 at 17 36 15](https://cloud.githubusercontent.com/assets/807084/6899857/4b0f8d70-d703-11e4-9553-a371b0f4c2a8.png)
