### ISSUE TITLE
Add a section in the Run page to display the event resource

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#229]
Corresponding issue in the SS Server: slipstream/SlipStreamServer#279

**Comment by rbf** [comment]
This story needs more details.

**Comment by schaubl** [comment]
I personally see the content of this section like the audit log of GitHub https://github.com/orgs/slipstream/audit-log (without the map).

**Comment by schaubl** [comment]
Looks like this issue is not anymore part of the Sprint v2.6.0, so I'm removing the milestone.

**Comment by rbf** [comment]
Overridden by #296.
Closing issue.
