### ISSUE TITLE
As Alice, I can provide or edit the input parameters when running an image, so that I don't need to create a deployment to achieve that.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#233]
### Description

Currently, the only way to provide or modify the input parameters of an image is when it is used as a node within a deployment. For images that make sense without the need of a deployment (e.g. a WordPress machine) it should be possible to provide or modify the input parameters directly from the "Run Image" dialog, in a similar way that is done for nodes in the "Run Deployment dialog".

### Upstream dependency

- [x] SlipStream/SlipStreamServer#170: Allow users to redefine "input parameters" for "Simple Run"

**Comment by rbf** [comment]
Will fix #199.

**Comment by schaubl** [comment]
The format of parameters to send to the SlipStream Server is the following:
`parameter--<parameter name>`

This is the same format used to select the Cloud.

Examples:
```
parameter--cloudservice = exoscale
parameter--admin_email = admin@example.com
```

**Comment by schaubl** [comment]
The corresponding branch in SlipStreamServer is `issue_#170-redefine_input_parameters`.

**Comment by rbf** [comment]
Done and pushed to branch [`issue_#233-redefine_input_parameters`](https://github.com/slipstream/SlipStreamUI/tree/issue_%23233-redefine_input_parameters).

![screen shot 2015-04-02 at 08 06 05](https://cloud.githubusercontent.com/assets/807084/6958640/3524ce4a-d90f-11e4-8cad-c186c14e50c5.png)

## Open question

What should be the behaviour if the user removes the values of the parameters?

Currently I have an unexpected behaviour: the request is sent correctly (see `curl` data below) but the server returns an error:

```curl
--data 'bypass-ssh-check=true&refqname=module%2Fneutral_projects_for_mockup_metadata%2Fapache_web_server%2F138&type=Run&parameter--cloudservice=Cloud2&tags=no-param-values&parameter--input_param_1=&parameter--input_param_2='
```

I obtain following unclear error:

```
ss:abort - Cloud Endpoint cannot be empty. . Please contact your SlipStream administrator.
```

I don't have this error if the parameters have some value:

```curl
--data 'bypass-ssh-check=true&refqname=module%2Fneutral_projects_for_mockup_metadata%2Fapache_web_server%2F138&type=Run&parameter--cloudservice=Cloud4&tags=with-parameters&parameter--input_param_1=default_value_for_input_param_1&parameter--input_param_2=default_value_for_input_param_2'
```
