### ISSUE TITLE
As Alice I can take a tour to learn the basics of SlipStream, such that I can get to ah ha faster

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#238]

**Comment by mebster** [comment]
Related to #191

**Comment by rbf** [comment]
Points noted during the demo of iteration `v2.7.0`:

- [x] Add a standard close button `x` to the dialog to start the tour.
- [x] Make step progress counter (`1/12`-like label at the top of the popover) relative to the **total** number of steps across the pages of the tour.
- [ ] In deployment page, merge the first step into the second (to stay within the modal dialog, and to make it more concrete).
- [ ] Add an `Congratulations`-like end slide, similar to the first one.
- [ ] When deployment is launched, wait for deployment done or for error, and react accordingly.
- [ ] `Guided tour` option in `Help` menu should not start the tour of the current page, but go to the welcome page and start the tour (after having asked for user confirmation).
- [ ] Add _page only_ tour to explain the main options and features of the page (see #285).
- [ ] Do no play recurrent jobs on tab `show` event, if they were disabled. In our case, we are stoping all them while the tour is running to avoid distractions and page changes, but if the user goes from the current tab, and comes back, currently the refresh job will be triggered once.

**Comment by schaubl** [comment]
This issue continue with the #286.

**Comment by rbf** [comment]
This issue continues with the #299.

**Comment by rbf** [comment]
This issue can now be closed.
The bugs after releasing the first beta of the tour are tracked in #345.
