### ISSUE TITLE
The noscript message is not working anymore.

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#240]
Looks like it's related to the following commit: e207b4aac4ade48d48245fa6215145b51d4d1e17
The `<noscript>` tag is not on the generated HTML.

**Comment by rbf** [comment]
Now the alert appears as follows:

![screen shot 2015-05-19 at 13 47 02](https://cloud.githubusercontent.com/assets/807084/7702083/b734fe30-fe2d-11e4-8f5e-f3d1b3f75fbf.png)
