### ISSUE TITLE
"contact us" link must use the configured support email contact

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#243]
Currently the support email contact for the "contact us" link is hardcoded to the SixSq support email address.  The address must be taken instead from the "SlipStream Support Email" address in the system configuration.  Community edition deployments in particular should _not_ by default contact SixSq support.

**Comment by rbf** [comment]
> Currently the support email contact for the "contact us" link is hardcoded to the SixSq support email address. The address must be taken instead from the "SlipStream Support Email" address in the system configuration.

Sure, makes sense and it can be easily done.

> Community edition deployments in particular should not by default contact SixSq support.

What should community edition do by default? How the UI side knows which edition it is generating the UI for?

**Comment by loomis** [comment]
For both editions the initial value should default to the value of the parameter, which should be something like "support@example.com".

**Comment by rbf** [comment]
@mebster 
How does this makes sense in the context of the Freshdesk support tabs?
Do we still have to offer this link in the help menu?

**Comment by mebster** [comment]
Good question. The ideal would be to have a customizable mechanism, such that by default Dave can set an email, while for say Nuvla we can set a link to our support page.
