### ISSUE TITLE
Dashboard: Add a subsection `All Runs` and `All VMs` on the sections `Runs` and `Virtual Machines`

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#252]
For the `All VMs` subsection, the column `Cloud` should be added.

**Comment by rbf** [comment]
@schaubl 
Can you please explain the rational behind this suggestion?

**Comment by mebster** [comment]
The fact that there's one cloud as seen by default is statistically likely not to be the one the user wants. Having a 'catch all' tab showing the most recent activity would increase the probability that user find his/her runs and vms.

An alternative to this is to have a link between the usage meter icon and the corresponding cloud in the run (or vm) section. We already have an issue for this.

**Comment by schaubl** [comment]
Initially I added this issue because of a comment made by @loomis.

Then I realized that it will be a very convenient feature because, for example, when I want to find a VM that I started recently, I'm always getting the VMs of the first Cloud (Amazon-EC2 in my case) but last time I used this Cloud was in November. So each time I have to click on an other subsection.
This is also why I created the issue #251 - *Provide direct link from the usage gages to the corresponding subsection on 'Virtual Machines' *

I completly agree with the previous comment from @mebster.
@mebster : See issue #251 which is about your second paragraph.

**Comment by rbf** [comment]
Thanks for the explanations.

I wonder if in that case this first _catch-all_ tab wouldn't be more useful with runs that are NOT in a final state (or vms that are still running). Maybe a global check box could allow the user to `include terminated runs`, affecting the results on all tabs (global and cloud-specific).

However I see the point discussed in this issue as a quick fix towards a more explicit (server-side) filtering of the content of those tables. The user should be able to choose at minimum the cloud(s) (this filter is currently emulated with the tabs), the state/status/on-off-status  and how many rows per page should be displayed. Making the result persistent would increase the probability that the finds the expected view the returning to the dashboard.

**Comment by rbf** [comment]
This issue was amended in the context of https://github.com/slipstream/SlipStreamUI/issues/353
Closing issue as duplicate.
