### ISSUE TITLE
Make the error reason more explicit

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#259]
User got confused: http://support.sixsq.com/helpdesk/tickets/254

**Comment by rbf** [comment]
Relevant detail from the screenshot in the ticket:

![screen shot 2015-03-31 at 15 28 07](https://cloud.githubusercontent.com/assets/807084/6919839/a528871e-d7ba-11e4-8f0d-ce105450e91b.png)

**Comment by rbf** [comment]
I assume this happened while creating a new SlipStream user in the HNX instance.
It would be useful to know with which username the user got this issue, since this is expected to be covered by the field validation:

![screen shot 2015-03-31 at 15 30 39](https://cloud.githubusercontent.com/assets/807084/6919907/061cdf70-d7bb-11e4-8c08-a4847c8d87c1.png)

**Comment by mebster** [comment]
I think it’s a different issue.

1. improving the validation
2. ensuring better readability of the error message

**Comment by rbf** [comment]
Ok, which issue is it then?

In order to understand and handle it properly we need to know:

a) how did the user get this error, and
b) which username was used to get this error.

**Comment by rbf** [comment]
And after a couple of tests, it indeed makes more sense to inverse the order and display the reason as title and the error code as text below:

![screen shot 2015-04-16 at 12 18 11](https://cloud.githubusercontent.com/assets/807084/7178912/fe362fb2-e432-11e4-994b-69c957478f23.png)

![screen shot 2015-04-16 at 12 10 39](https://cloud.githubusercontent.com/assets/807084/7178910/fe30205e-e432-11e4-9936-4f24b7480588.png)

![screen shot 2015-04-16 at 12 17 33](https://cloud.githubusercontent.com/assets/807084/7178911/fe33f72e-e432-11e4-9330-dd0e460d6f20.png)

The only drawback would be if there are long texts for the reason. I haven't found any playing with the usual errors (`reference not available`, `Failed terminating VMs`).

@slipstream/owners Can somebody confirm that there are not very long texts in error responses for `PUT` and `POST` requests? (i.e. nothing to do with the `ss:abort` messages.)

**Comment by mebster** [comment]
Even if it's long, we could clip it?

**Comment by rbf** [comment]
Indeed. So, as discussed, to prevent edge cases of alerts with very long title or message, we now (bd63512) trim them to a max length of 500 of 1500 respectively:

![screen shot 2015-04-17 at 11 11 10](https://cloud.githubusercontent.com/assets/807084/7199212/242273c8-e4f3-11e4-8fff-7b07d2cce160.png)

NB: This is done for all types of alerts, not only in the case of AJAX error messages enhanced above with commit 3bb5ede.
