### ISSUE TITLE
As a SlipStream user, I can choose the language of the web application interface among a list of supported languages.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#274]
Some discussion should happen to agree on how to implement that. See original comment from @schaubl in the related issue #269.

**Comment by rbf** [comment]
In order to know which `locale` to use, I suggest to keep it simple and use a persisted value in the `user` DB object using `en` by default.

**Comment by mebster** [comment]
We could mimic the quota behaviour, where there's a system wide default parameter, which can be changed at the user level.
