### ISSUE TITLE
Image module in the Edit mode shouldn't allow to change Category of the Coordination Parameter

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#278]
The updated Category of the parameter is not persisted server side anyways.

It should be made clear that the choice of the parameter category is allowed to be made only during the initial definition of the parameter.  Any changes later on don't take any effect.

**Comment by rbf** [comment]
This has been discussed several times, and no clear decision was taken about which behaviour we want (i.e. allow or not the category `input`/`output` of a parameter to be changed) and thus which side to fix (i.e. if the server should accept a change in the category of the parameter or if the UI should prevent it).

**Comment by schaubl** [comment]
We have to make sure that the behaviours of the UI and the Server are coherent, which is currently not the case.
@meb: I'm adding the label `Discussion` and `Shortlisted for Sprint`.

**Comment by rbf** [comment]
For reference, with the previous commit 599051b it looks like follows:

![screen shot 2015-05-19 at 16 28 10](https://cloud.githubusercontent.com/assets/807084/7705433/7c2afa4e-fe44-11e4-9f51-67005b22ac79.png)
