### ISSUE TITLE
Error icon placed on the wrong section

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#279]
![screen shot 2015-04-10 at 12 08 34](https://cloud.githubusercontent.com/assets/419519/7086484/dc77a2e4-df81-11e4-8eb2-aebddfe63fa1.png)

**Comment by rbf** [comment]
Can you please clarify the issue:
- I don't see any error icon in the screenshot. What are you expecting to see?
- Which version and service are you using? It doesn't look like the last UI version. In `v2.6.1` the dashboard looks like this:
![screen shot 2015-04-10 at 12 21 17](https://cloud.githubusercontent.com/assets/807084/7085991/72fae808-df7c-11e4-99a5-378166f6a4c5.png)

Cheers.

**Comment by mebster** [comment]
My bad... wrong image

**Comment by rbf** [comment]
In the screenshot, the "warning" icon is placed in the first section because the must be a warning there.
Rejecting and closing issue.
