### ISSUE TITLE
Unclear dropdown value to set default value

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#280]
I don't think 'Default value' for the dropdown is right. 'Set value' perhaps?
![screen shot 2015-04-10 at 12 10 47](https://cloud.githubusercontent.com/assets/419519/7086535/8a804a76-df82-11e4-88a0-56210a2fec2d.png)

**Comment by rbf** [comment]
Can you please clarify the issue:
- I don't see any error dropdown in the screenshot. What are you expecting to see?
- Which version and service are you using? It doesn't look like the last UI version. In `v2.6.1` the dashboard looks like this:
![screen shot 2015-04-10 at 12 21 17](https://cloud.githubusercontent.com/assets/807084/7085991/72fae808-df7c-11e4-99a5-378166f6a4c5.png)

**Comment by mebster** [comment]
Same here :-(
