### ISSUE TITLE
Clicking on usage dial puts invalid URL in browser

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#346]
E.g.: https://nuv.la/dashboard+exoscale-ch-gva#deployments--runs--builds+exoscale-ch-gva

So if we refresh the page after clicking on a dial in the Usage section, we get a 404.

**Comment by rbf** [comment]
This is not a direct issue with the usage dials on the dashboard but with the mechanism which persists the open subsection in the `#` of the URL.
I'm fixing it now since it affects several pages.

**Comment by rbf** [comment]
The previous commit 2d7e543 also fixes the annoying and unnecessary `#` with the default open section when landing on any page and without opening another section. Now the `#` will be added with the current `section+subsection` titles only when actively opening a section.

Note that if you open a link which already contains a `#`, the corresponding section/subsection will be opened and it will not be removed from the hash. However, if the  section/subsection does not exist, it will be removed from the `#` and the default one will be opened.
