### ISSUE TITLE
reshuffle dashboard and app store to improve functionality

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#353]
Bring the dashboard as the main interface page and move the app store to a secondary page.

**Comment by rbf** [comment]
As agreed in today's discussion, we'll begin by offering a cleaner and more functional layout in the dashboard (see screenshot below). The changes include:

- [ ] Display usage as a flat section at the top
- [ ] Merge the `Runs` and `VMs` tables for the selected usage gauge in two subsections in a flat section after the usage gauges
- [ ] Leave the `Metering` sections as is now, as the last section
- [ ] Include a global `All` usage gauge
- [ ] Add the column `Cloud` to the `VMs` subsection table (at least for the `All` view)
- [ ] Review Alice's tour to match the new Dashboard layout

![screen shot 2015-06-29 at 11 48 37](https://cloud.githubusercontent.com/assets/807084/8405757/08599d7c-1e57-11e5-883e-0e53d2684e70.png)

Later on (issues to be created) we will progressively implement the following points:

- [ ] Use dashboard as a landing page
- [ ] Include an option in the `Runs` subsection to `Include terminated runs`
- [ ] Think about moving the metering section as a subsectoin tab net to `VMs`

**Comment by rbf** [comment]
State of the dashboard layout implemented with this issue:

![screen shot 2015-07-09 at 13 51 43](https://cloud.githubusercontent.com/assets/807084/8598516/5d32760a-265b-11e5-852a-36b569a34a31.png)
