### ISSUE TITLE
Create an HTML template to be used in the usage emails.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#354]
Related to slipstream/SlipStreamServer#347, @st.

Test HTML email on common email clients, like:

- [ ] Apple Mail (Mac OS X)
- [ ] Apple Mail (iOS)
- [ ] Outlook (2000, 2002, 2003)
- [ ] Outlook (2007, 2010, 2013)
- [ ] Outlook (2011)
- [ ] Thunderbird
- [ ] Android
- [ ] Gmail (Desktop)
- [ ] Gmail (Mobile, iOS, Android)
- [ ] Outlook 2011 for Mac
- [ ] AOL Mail
- [ ] Hotmail
- [ ] Outlook.com

**Comment by st** [comment]
http://templates.mailchimp.com/development/testing-emails/
