### ISSUE TITLE
Disable "Fancy a tour?" option for non-production environments

### ISSUE THREAD

**Issue by vincent-legoll** [slipstream/SlipStreamUI#356]
Would it be possible to add an option to disable the "Fancy a tour?" popup.
For example if you're testing or doing development, etc...

**Comment by rbf** [comment]
[[Original place](https://github.com/slipstream/SlipStreamConnectors/issues/34#issuecomment-114830453) of this comment was in issue slipstream/SlipStreamConnectors#34]

In the meantime, does it work for you to disable it when asked? (see button highlighted in the screenshot below)

![disable_tour](https://cloud.githubusercontent.com/assets/807084/8328676/06764b1e-1a73-11e5-98bc-8b6efdf3acb2.png)

> Maybe the way is in modifying the code locally...

You might outcomment the JS code that starts it:

https://github.com/slipstream/SlipStreamUI/blob/master/clj/resources/static_content/js/tours/alice-intro-welcome.js#L59-L67

**Comment by mebster** [comment]
Is the annoying mention required?

**Comment by vincent-legoll** [comment]
OK done ;-)

**Comment by mebster** [comment]
Thanks. Very much appreciated :-)

**Comment by vincent-legoll** [comment]
I have overlooked the other button. Its working as intended
