### ISSUE TITLE
Improve image page regarding recipe workflow

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#362]
The intended usage of recipe vs execute script is opaque to users. Improve this by integrating the recipes, taking into account winter retreat prototype (see Lionel's mockup)

**Comment by mebster** [comment]
Could also extend this to a review of the image page.

**Comment by rbf** [comment]
I need more context to estimate the size. Will do during planning meeting.

**Comment by rbf** [comment]
@mebster 
>  (see Lionel's mockup)

I don't see it. :stuck_out_tongue_winking_eye: 
Is it still available somewhere?

Otherwise, my understanding is to show all recipes in one same section, ordered by execution time. Is that right?

**Comment by rbf** [comment]
Mockup is in #121.
Thanks @mebster.

**Comment by rbf** [comment]
@mebster 
Is something like this what you have in mind?

![screen shot 2015-08-25 at 12 02 48](https://cloud.githubusercontent.com/assets/807084/9464110/8b12c3be-4b21-11e5-8914-2ce730d3ba06.png)

Cheers.

**Comment by mebster** [comment]
Custom Scripts -> Scripts or Behaviour or Workflow?

Parameters should be in a different section.

We also need to indicate which scripts will be execute as part of a create image (if supported by the cloud).
