### ISSUE TITLE
UI should notify user about any unsuccessful attempt to perform server-side call

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#372]
In the case below there was 1 min gateway timeout on POST to `run/` after clicking `Run... -> "Run Deployment"`, but the UI hid this error and user was left unaware of what has happened.  Only debugging mode in the browser revealed the server-side issue:

<img width="1437" alt="screen shot 2015-07-13 at 15 26 22" src="https://cloud.githubusercontent.com/assets/353767/8650602/36936bf0-2974-11e5-8ebb-405e0f029add.png">

**Comment by rbf** [comment]
@konstan Thanks for reporting this.
You added this directly into the ongoing iteration.
Is it intentional?

**Comment by konstan** [comment]
@rbf (Sorry. Just noticed your comment.) 
Yes, I added this to the iteration intentionally.  At the moment, looks like there is this https://github.com/slipstream/SlipStreamServer/issues/419 bug in SS and at the beginning from the user side (in CELAR project) it was difficult to figure out what the problem was.

**Comment by rbf** [comment]
Ok, thanks. I'll have a look. Cheers.

**Comment by rbf** [comment]
@konstan After our discussion this morning, I think #208 makes sense to be implemented together with (or before) this issue. I moved #208 into the iteration and I'm working now on both this issues.

**Comment by rbf** [comment]
FYI #368 is related to this (also an AJAX call related issue) and must be also fixed at the same time.

**Comment by rbf** [comment]
For reference, the UI did already _notify user about any unsuccessful attempt to perform server-side call_, including unexpected `5xx` like the one discussed in this issue. The problem here was a bug when handling AJAX responses in `text` format.
