### ISSUE TITLE
ss-run-set

### ISSUE THREAD

**Issue by sw-irou** [slipstream/SlipStreamUI#38]
When using slipstream to store parameters for other management systems, it would be useful to be able to use ss-run-set (akin to ss-set, but using most of the syntax of ss-run-get).

e.g.
ss-run-set -uuser -ppassword --endpoint=slipstream.example.com 0c1d1212-1753-47cf-9fb6-486bb9dd7873 key newvalue

**Comment by rbf** [comment]
Discussed with @loomis. This issue is outdated. Closing issue.
