### ISSUE TITLE
Report orch VM failures

### ISSUE THREAD

**Issue by sw-irou** [slipstream/SlipStreamUI#39]
It would be useful if orch VMs failing to finish their deployment were automatically investigated (via ssh) by the slipstream server after a certain amount of time failing to report back- e.g. due to an intervening firewall or similar.

To aid in troubleshooting it would also be good if the orch VM would then try to email a failure report if it couldn't report and didn't get contacted by the slipstream server in a given time period.

**Comment by rbf** [comment]
Discussed with @loomis. This issue is outdated. Closing issue.
