### ISSUE TITLE
UI on Run page may not show the state of the run

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#394]
The Run was aborted, but the UI doesn't show the state after `Run: 71ca7f1f is`

<img width="1277" alt="screen shot 2015-07-31 at 12 25 35" src="https://cloud.githubusercontent.com/assets/353767/9005561/80c793cc-377f-11e5-9f9c-016de44bc4c1.png">

After refreshing with `Cmd+Shift+R` the UI shows the state.

<img width="1274" alt="screen shot 2015-07-31 at 12 28 03" src="https://cloud.githubusercontent.com/assets/353767/9005563/85a29a22-377f-11e5-8f88-6d1182daf4e9.png">

**Comment by rbf** [comment]
I'm not able to reproduce it. Can you please share the steps to encounter this issue?
Cheers.

**Comment by konstan** [comment]
Unable to reproduce.  Closing.
