### ISSUE TITLE
add VM terminate button to dashboard

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#399]

**Comment by loomis** [comment]
See ticket #395 and referenced fresh desk ticket.

**Comment by rbf** [comment]
As per the [SS API Documentation](http://ssapi.sixsq.com/#virtual-machines) there is currently no request for terminating a VM. Is that correct?

This is related to the corresponding task in the server: https://github.com/slipstream/SlipStreamServer/issues/85

**Comment by schaubl** [comment]
> As per the SS API Documentation there is currently no request for terminating a VM. Is that correct?

Yes.
The internal command that SlipStream uses, only terminate VMs but on the level of the API, we can only terminate Runs.
