### ISSUE TITLE
Modifiying ACL doesn't apply while user is logged in

### ISSUE THREAD

**Issue by zyegfryed** [slipstream/SlipStreamUI#40]
When giving access rights to a group, a user belonging to the targeted group must sign-out and sign-in again to have its rights updated.
User should be granted access while connected.

**Comment by rbf** [comment]
New UI (version > 2.4) doesn't has this bug.

This applies:
> The change will be applied to next version increment. So simply access the latest version of that module to access the ACL change.

Closing issue.
