### ISSUE TITLE
add service.url link to dashboard

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#400]

**Comment by rbf** [comment]
The `service.url` value is currently not included in the `run` items returned by the `/run?media=xml` route. Therefore, the `server` has to be modified as well to add it, probably in the [persistence/Run.java](https://github.com/slipstream/SlipStreamServer/blob/aed2a7025dd738cdec6b57c789c5f7078fb3e821/jar-persistence/src/main/java/com/sixsq/slipstream/persistence/Run.java#L328-L329) class. I haven't found the corresponding issue in the `SlipStreamServer` repo, though. I'd be happy to pair-programm on that task with somebody else.

Once the attribute is included in the runs list, it's trivial to include it in the dashboard tables. I'm assigning a size of `1` to this task assuming the previous work is done before.

**Comment by sixsq-hudson** [comment]
Can you create an issue on the server and assign it to me?

**Comment by rbf** [comment]
Done. See: https://github.com/slipstream/SlipStreamServer/issues/451
