### ISSUE TITLE
make input/output parameters usable from UI

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#402]

**Comment by rbf** [comment]
@loomis
Can you please provide more context for this task?
Cheers.

**Comment by loomis** [comment]
See slipstream/SlipStreamServer#446.

**Comment by rbf** [comment]
This issue is outdated. Flagging it as `✖︎ Outdated - Flagged for deletion` for discussion.

**Comment by schaubl** [comment]
AFAIK there is nothing to do in the UI except reenabling the dropdown menu in non-new edit mode.
The corresponding task in the Server repo is enough.
Closing it.
