### ISSUE TITLE
Spinner spins forever on dashboard when no deployment

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#407]
![screen shot 2015-08-17 at 12 25 50](https://cloud.githubusercontent.com/assets/419519/9302995/3e75158a-44db-11e5-81d1-33746f683b42.png)

**Comment by rbf** [comment]
This is surely related to the fact that the new dashboard design does not play well with the quota disabled.

With quota enable the expected message is displayed when there is nothing to display:

![screen shot 2015-08-17 at 15 04 46](https://cloud.githubusercontent.com/assets/807084/9305435/c42a0d28-44f1-11e5-8499-c9eb6644aa7c.png)

**Comment by rbf** [comment]
This was fixed a while ago and is already in production. Even without the `quota` option enabled (i.e. no usage gauges shown), the deployments tab does not spin forever:

![screen shot 2016-04-14 at 17 56 38](https://cloud.githubusercontent.com/assets/807084/14534667/74c4906e-026a-11e6-9230-00dbb7d3c5d6.png)

Closing issue.
