### ISSUE TITLE
add start button to dashboard

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#420]
Add a start button to the dashboard to bring up a dialog that would allow an application to be selected.  Once selected the usual "Run..." dialog should be presented to start the application.  During all of this, the user should still be on the dashboard.

**Comment by mebster** [comment]
Extend this to support 're-run' behavior where the previous parameters are filled in the run... dialog.

**Comment by rbf** [comment]
@loomis:

> Add a start button to the dashboard to bring up a dialog that would allow an application to be selected. Once selected the usual "Run..." dialog should be presented to start the application. During all of this, the user should still be on the dashboard.

- Is this a button on the normal (secondary) menubar (where the `Run...` action is in the module pages)? 
- And then, the application to be selected could be a the App Store into a modal dialog?

@mebster:

> Extend this to support 're-run' behavior where the previous parameters are filled in the run... dialog.

- OTOH this would be an icon next to the new `Terminate` action in the run table itself, right? Or what you do you mean by _Extend this..._?
- And is there currently a way to retrieve the used parameters for a given run, or does it still have to be implemented?

**Comment by loomis** [comment]
The "global" start button could be in the secondary menu, although it might make sense to bring it closer to the listing of runs.  The application selection would need to be in a dialog, both the App Store and the hierarchical listing of modules would need to be available.  Perhaps turning the sections into tabs in the dialog would avoid having to scale down to see other sections.

It seems that the feature requested by @mebster is a separate set of buttons which would replace the terminate buttons with a "Restart" button for terminated runs. It would avoid the initial application selection dialog for the given run as the information could be taken from the old run.  I'm not sure about the terminology of the button.  Both "start" and "restart" would seem to indicate resuming an application instance rather than creating a new application instance with the same configuration.
