### ISSUE TITLE
refactor javascript for conditional loading of support/analytics

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#427]
Determine how to conditionally load the javascript file for the SlipStream server to allow customized `support.js` and Google analytics file to be loaded dynamically.

**Comment by schaubl** [comment]
Currently support.js is marked as a configuration file in the RPM so an empty one is provided with the RPM and then the user can update it and it will not be overwritten by updates.

**Comment by loomis** [comment]
That works if you want to manage the file by hand, but doesn't work if you want to manage it via a package.  If the same file (with different content) is in more than one RPM package, then `rpm/yum` will refuse to install it, complaining about a file conflict.

**Comment by schaubl** [comment]
> That works if you want to manage the file by hand, but doesn't work if you want to manage it via a package. If the same file (with different content) is in more than one RPM package, then rpm/yum will refuse to install it, complaining about a file conflict. 

Yes, you're right. I just wanted to mention how this feature is implemented for now.
But we can improve it for example by not providing the file with SlipStream and add a conditional loading (load if the file exist) in the UI so that the browser will not request a file which doesn't exist.
