### ISSUE TITLE
configuration section "SlipStream Support" should be renamed to "Email Parameters" or similar

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#43]
The second named "SlipStream Support" doesn't really convey the contents of that section.  All of the parameters deal with email, so something like "Email Parameters" would be more useful.

**Comment by rbf** [comment]
I find this still relevant. Promoting to `S05 Ready to work`.

**Comment by rbf** [comment]
@loomis 
Do you still think the renaming is worth it?

**Comment by sixsq-hudson** [comment]
Yes, at least in the UI.

**Comment by rbf** [comment]
Still relevant. Promoting to `S02 Shortlisted for Sprint`.

**Comment by rbf** [comment]
Overridden by #304.
Closing issue.
