### ISSUE TITLE
For UI using 'default' theme after installation from scratch the theme images are not available

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#444]
Right after the installation this file is not accessible:  
https://185.19.29.53/themes/default/images/logo-menubar-unlogged.png 
because there is no `default` theme under `themes`.

If 'default' corresponds to 'nuvla', then a simple link can easily solve the issue

```
[root@slipstream12108487d-b62e-4ce3-a6dd-f07209765f2d themes]# ll
total 8
lrwxrwxrwx. 1 root       root          6 Oct  5 11:05 default -> nuvla/
drwxrwxr-x. 6 slipstream slipstream 4096 Oct  5 10:39 helixnebula
drwxrwxr-x. 4 slipstream slipstream 4096 Oct  5 10:39 nuvla
[root@slipstream12108487d-b62e-4ce3-a6dd-f07209765f2d themes]# 
```

**Comment by rbf** [comment]
Please make sure that `-Dslipstream.ui.util.theme.current-theme=nuvla` is used when starting the SlipStream `jar`.
Does it solve the issue?

**Comment by konstan** [comment]
Closing the issue.  Opened #447 instead.
