### ISSUE TITLE
Allow to execute a script on the orchestrator

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#445]

**Comment by rbf** [comment]
As clarified by @mebster, this task aims to add a Section to the Deployment page similar to the "Application Workflows" in the Image page where the user can insert a script that will be executed on the `orchestrator` nodes.

The wording used in this new section is still to be decided.

**Comment by schaubl** [comment]
See the following tickets:
- https://github.com/slipstream/SlipStreamServer/issues/494
- https://github.com/slipstream/SlipStreamClient/issues/139

**Comment by rbf** [comment]
- [ ] Make title of the section `Orchestrator Workflows` => `Application Workflows`
- [ ] Mark it as experimental: `1. Deployment` => `Deployment (experimental)`

**Comment by rbf** [comment]
Labels updated according to points above:

![screen shot 2015-12-03 at 14 01 19](https://cloud.githubusercontent.com/assets/807084/11561495/14e99aaa-99c8-11e5-849c-7268c365c304.png)
