### ISSUE TITLE
Use SS default theme when started with 'default' for slipstream.ui.util.theme.current-theme property

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#447]
Rationale: this simplifies configuration process.

Retain the ability to use SS default theme when `slipstream.ui.util.theme.current-theme` property is not provided.

**Comment by konstan** [comment]
Just a thought.  What if UI would use default theme if
- `slipstream.ui.util.theme.current-theme` is not provided at all
- `slipstream.ui.util.theme.current-theme` is given a value for which theme is not found.

**Comment by rbf** [comment]
- [ ] Add a log trace about the used theme.

**Comment by rbf** [comment]
I've added some logging related to the theme. Here are the possible cases:


1. If the system property `slipstream.ui.util.theme.current-theme` is not setup or its value is a blank string, the default theme is used and the logs report the following:

    ```
    INFO: Using theme "default"
    ```

1. If the system property `slipstream.ui.util.theme.current-theme` is setup to the string `default`, the default theme is used and the logs report the following:

    ```
    INFO: The system property 'slipstream.ui.util.theme.current-theme' has the value: "default"
    INFO: Using theme "default"
    ```

1. If the system property `slipstream.ui.util.theme.current-theme` is setup to an unknown theme, the default theme is used and the logs report the following:

    ```
    INFO: The system property 'slipstream.ui.util.theme.current-theme' has the value: "asdf"
    WARN: The requested theme "asdf" is not available. Must be one of "nuvla", "helixnebula" or "default".
    INFO: Using theme "default"
    ```

1. If the system property `slipstream.ui.util.theme.current-theme` is setup to a known theme, the given theme is used and the logs report the following:

    ```
    INFO: The system property 'slipstream.ui.util.theme.current-theme' has the value: "nuvla"
    INFO: Using theme "nuvla"
    ```
