### ISSUE TITLE
Large Run should update state of the run in the UI header

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#458]
On `Large Run` (21+ VMs) the auto-refresh of the runtime parameters (RTPs) is disabled.  For the users it's not clear that the state of the run is also a global RTP of the run.  So, we either have to explicitly say that, to see the latest state of the run please reload the page, or dynamically fetch `ss:state` RTP and update in the UI header.

**Comment by rbf** [comment]
This is the current warning for large runs:

![screen shot 2015-10-26 at 11 06 19](https://cloud.githubusercontent.com/assets/807084/10726244/bc7cac0e-7bd1-11e5-872f-b1061d423957.png)

Would following message be more clear for the point you state above?

> This is a large run with a total of 25 node instances. The auto-refresh of the page is disabled. Please refresh it manually or go to the Dashboard [link], where the overall status of all runs is continuously auto-refreshed.

**Comment by konstan** [comment]
IMO the state of the run displayed to the user on the run page itself
should be consistent with its state according to the state machine.
What are the difficulties with querying and displaying the proper value?
If the difficulties are really big, then in the first approximation the
proposed solution looks OK.

On Mon, Oct 26, 2015 at 11:12 AM, rbf <notifications@github.com> wrote:

> This is the current warning for large runs:
>
> [image: screen shot 2015-10-26 at 11 06 19]
> <https://cloud.githubusercontent.com/assets/807084/10726244/bc7cac0e-7bd1-11e5-872f-b1061d423957.png>
>
> Would following message be more clear for the point you state above?
>
> This is a large run with a total of 25 node instances. The auto-refresh of
> the page is disabled. Please refresh it manually or go to the Dashboard
> [link], where the overall status of all runs is continuously auto-refreshed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/slipstream/SlipStreamUI/issues/458#issuecomment-151089738>
> .
>



-- 
Cheers,
Konstantin Skaburskas
SixSq
