### ISSUE TITLE
Broken link to documentation

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#461]
The following link must be updated: http://ssdocs.sixsq.com/documentation/advanced_tutorial/SlipStream_Client.html#major-client-commands
In the help message on the Application Workflow for target 4 - 7.

**Comment by loomis** [comment]
The link should be adjusted to point to the top of the tutorial rather than deep-linking into the documentation.  Deep links are not likely to be stable with revisions of the documentation.

**Comment by rbf** [comment]
Done, together with a couple of additional remaining legacy documentation links.
I've created PR #462 for that and assigned it to @mebster.

@loomis I've also removed the `#` as you suggested to point to the top of the page in all the corrections.

BTW, the table for the [major client commands](http://ssdocs.sixsq.com/en/latest/advanced_tutorial/SlipStream_Client.html#major-client-commands) is not well rendered in RTFD:

![screen shot 2015-11-02 at 10 44 16](https://cloud.githubusercontent.com/assets/807084/10878557/b2ac8db6-814e-11e5-9baf-c816a02f6412.png)

**Comment by loomis** [comment]
@rob: Actually I'd suggest just linking to the root of the advanced tutorial and use text to describe where to find the detailed information.  The sections themselves (and the links) are likely to be significantly restructured for the upcoming tutorial and some may disappear entirely.

**Comment by rbf** [comment]
@loomis Done with commit ff3047e above.
