### ISSUE TITLE
Provide an ability to see Application Component execution targets on the Run

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#464]
This will streamline the troubleshooting of the Application deployment.

**Comment by rbf** [comment]
Thanks for the feedback :) What is the issue in the current design, where you can to the referenced version of the deployed component? There is a link to that.

**Comment by konstan** [comment]
In the case of the run started as deployment of an application (probably multi-component one), to go to the per-component deployment scripts would require minimum four clicks: 

- breadcrumb link to the application deployment (where a mistake can be made by clicking on the module name instead of version number - which in the end may lead you to a different version of the Component and effectively to a different script)
- link to the Component
- tab with the Application Workflows
- tab with Deployment

And all this should be done in a separate browser tab as well, because we want to see and correlate the behaviour of the Deployment script with the RTPs being set from it on the node instance in the run.

So, the idea would be to have an ability to see and scroll through the Deployment script of the Component while you are on the run and in the tab of the Component (node).  I see it being similar to pressing `Space` when in `Finder` on Mac with a text file selected - i.e. getting an scrollable preview of the text.  

The per-component scripts are already available on the Run as `<run><module><nodes><entry><node><image><targets><target name="execute">`.

**Comment by rbf** [comment]
I see now, thanks. Makes sense.
