### ISSUE TITLE
Improve dashboard by facilitating the identification of active runs and vms

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#472]
Order runs and vms in dashboard with 'active' resources first. Or alternatively allow for only displaying 'active' resources.

We also need to look at the corner case: when a run in 'done' but a VM is still running (which is an error case).

**Comment by rbf** [comment]
This has been mentioned multiple times now. There are even old issues about it (see #153, #186, #252 and https://github.com/slipstream/SlipStreamServer/issues/352). The preferred implementation is to add a basic filter option to hide the `terminate`d runs. As discussed, this filtering should happen server side to allow proper pagination (see https://github.com/slipstream/SlipStreamServer/issues/352 referenced above).

I'm closing now #153 as duplicate, even if it has such a nice number[.](http://www.shyamsundergupta.com/c153.htm)

**Comment by rbf** [comment]
## Upstream dependency:

- [ ] https://github.com/slipstream/SlipStreamServer/issues/573: simple filter on active runs

**Comment by rbf** [comment]
@konstan I've added a the query parameter `includeTerminated` in the URL of the runs table, which can be `0` or `1`. With that, the full URL for the runs becomes:

```
/run?cloud=&offset=0&limit=20&moduleResourceUri=&includeTerminated=1
```

![screen shot 2015-12-09 at 17 40 01](https://cloud.githubusercontent.com/assets/807084/11691578/f05c6cca-9e9b-11e5-9abd-4da917626b73.png)

Will that fit your requirements server side?

 NB: This is still to be merged into `master`.

**Comment by rbf** [comment]
After a discussion with @schaubl and @konstan we agreed to reverse the meaning of the API query parameter (renaming it from `includeTerminated` to `activeOnly`), while leaving the _include inactive runs_ meaning on the UI. With that, the full URL for the runs becomes:

```
/run?cloud=&offset=0&limit=20&moduleResourceUri=&activeOnly=1
```

On top of that, we added a tooltip:

![screen shot 2015-12-10 at 17 09 45](https://cloud.githubusercontent.com/assets/807084/11720736/df50d0e0-9f60-11e5-98f3-e1a6220d7185.png)
