### ISSUE TITLE
In dashboard dials, also show unknown VMs

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#473]
This is to alert the user that SlipStream sees resources running that it either doesn't know about, or that it knows about but belong to other users.

**Comment by rbf** [comment]
This has been mentioned a couple of times already. Globally I agree that this would help the user understanding the status of the related clouds. However, as suggested by @loomis, the _unknown_ VM should be displayed in a different manner (e.g. with a grey color) in the gauge to make clear that their are not managed by SlipStream.

**Comment by mebster** [comment]
As discussed with @loomis during the planning meeting preparation, there are three cases:
1. My VMs from my runs
1. VMs started by others using SlipStream, with which I share cloud accounts
1. VMs SlipStream is unaware of (started by me or others if I'm sharing accounts)

All these should be shown on the dial, with different importance (e.g. gray number for unknown for example is a good idea).  We also might indicate that x number of users are sharing the same connector credentials, such that there are no surprises.
