### ISSUE TITLE
Prevent that the fields to create a new user can be auto-filled by the browser.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#476]
These fields exist in two places: the auto-sign-up form in the login screen and the "Create new user" form available to admins.

For reference, this was the cause that allowed @mathiasslawik to create a username with a dot, since the JS validation rules (which normally prevent this) were not triggered by the auto-filling (see #474). In this case it was on Chrome.

**Comment by loomis** [comment]
Add final validation of the fields before sending request to server.
