### ISSUE TITLE
unit tests in interop_test.clj fail with clojure 1.8.0-RC1

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#480]
The tests in `interop_test.clj` fail when moving to the latest clojure version.  The errors occur because of new classes/interfaces added in clojure 1.8.0.  These need to be corrected before moving to clojure 1.8.0. It would be ideal if these tests could be fixed in a way that allows them to work for all of the current versions of clojure. 

The errors occur in the tests that check the ancestors of:
 - `clojure.lang.PersistentArrayMap`
 - `clojure.lang.PersistentHashMap`
 - `clojure.lang.PersistentVector`

Because of the addition of the following interfaces or extended classes:
 - `clojure.lang.IKVReduce`
 - `clojure.lang.IMapEntry`
 - `java.util.Map$Entry`

**Comment by rbf** [comment]
For reference:
- Release notes for [Clojure 1.8](https://github.com/clojure/clojure/blob/master/changes.md#changes-to-clojure-in-version-18) on GitHub.
- Release notes for [Clojure 1.8](http://dev.clojure.org/jira/secure/ReleaseNote.jspa?projectId=10010&version=10254) on Jira.

**Comment by rbf** [comment]
Closing since done a while ago.
