### ISSUE TITLE
duplicate hostname parameter is allowed

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#488]
The UI (and perhaps the server as well) allows duplicate hostname parameters.  This should raise an error immediately rather than resulting in failed deployments.

**Comment by rbf** [comment]
This is still the case in production:

![screen shot 2016-04-14 at 18 29 05](https://cloud.githubusercontent.com/assets/807084/14535606/d79ae982-026e-11e6-8503-8036d4e6e53e.png)

Promoting to `Proposed for Sprint`.
