### ISSUE TITLE
Subsections are not remembered in the hash of the URL for the first section.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#492]
Because since the first section is open by default, the id of the section in not added in the hash of the URL.

**Comment by st** [comment]
Trace:
```
Uncaught Out of bounds! 
Current hash only contains 0 values. Indexes are 0-based.(anonymous function) 
@ util.js:2085m.extend.each 
@ jquery-1.11.1.min.js:2util.url.hash.updateValues 
@ util.js:2083(anonymous function) 
@ subsection.js:72m.event.dispatch 
...
```

**Comment by rbf** [comment]
This bug is still present on production:

![screen shot 2016-04-14 at 18 24 03](https://cloud.githubusercontent.com/assets/807084/14535448/32fd5b4e-026e-11e6-8aec-22f6190bf137.png)

The only pages that have subsections on the first section, which is open by default, are `/events` and `/usage`.

Since this bug is not very difficult to fix, I'm promoting it to `Proposed for Sprint`.
