### ISSUE TITLE
Cloudsigma connector not stable beacsue of paramiko.transport..

### ISSUE THREAD

**Issue by yazun** [slipstream/SlipStreamUI#5]
No handlers could be found for logger "paramiko.transport" Traceback (most recent call last): File "/usr/bin/cloudsigma-run-instances", line 122, in <module> MainProgram() File "/usr/bin/cloudsigma-run-instances", line 15, in __init__ super(MainProgram, self).__init__() File "/usr/lib/python2.6/site-packages/com/sixsq/slipstream/cloudconnectors/cloudsigma/CloudSigmaCommand.py", line 9, in __init__ super(CloudSigmaCommand, self).__init__() File "/usr/lib/python2.6/site-packages/com/sixsq/slipstream/cloudconnectors/CloudClientCommand.py", line 19, in __init__ self.doWork() File "/usr/bin/cloudsigma-run-instances", line 76, in doWork node = self._startImage(ss_node) File "/usr/bin/cloudsigma-run-instances", line 91, in _startImage self.options.ssh_password) File "/usr/lib/python2.6/site-packages/com/sixsq/slipstream/cloudconnectors/BaseCloudConnector.py", line 570, in _waitCanConnectWithSshOrAbort raise Exceptions.ExecutionException("Failed to connect to %s: %s" % (host, str(ex))) com.sixsq.slipstream.exceptions.Exceptions.ExecutionException: Failed to connect to 185.12.7.108: Error reading SSH protocol banner[Errno 104] Connection reset by peer

**Comment by rbf** [comment]
@schaubl This seems like an obsolete issue. Do you confirm we can close it? Cheers.

**Comment by schaubl** [comment]
Yes, and it's definitely not related to the UI.

**Comment by rbf** [comment]
:+1: Thanks. Closing issue.
