### ISSUE TITLE
update ServiceInfo visualization to use attribute resource

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#506]
Update the ServiceInfo visualization to use the attribute resource.

**Comment by rbf** [comment]
@loomis: Can you please detail this issue a bit more. E.g. add a screenshot if im makes sense. Thanks.

**Comment by loomis** [comment]
The data for the name, description, etc. should be taken from the new attribute resource rather than from a static file as is currently the case.  The displayed information is essentially the same as shown by @st in the last demo, just taken from a different source.

**Comment by st** [comment]
Two enhancements for the visualisation:
* If possible, show the composite nature of an attribute
* Add full URI when hovering over the name

**Comment by st** [comment]
See https://github.com/SixSq/SlipStreamServer/pull/3#issuecomment-162877929
