### ISSUE TITLE
Description field of output RTP is not saved after editing of a component

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#514]
I see this on v2.19.1 on nuv.la.  I haven't checked this on deployments from `candidates` repo. 

Changing the description of `ss-repo-conf-url` to "Foo bar baz".
<img width="512" alt="screen shot 2015-12-09 at 10 21 25" src="https://cloud.githubusercontent.com/assets/353767/11681467/756bad82-9e5f-11e5-9240-d5baa5b50305.png">

After saving the description of `ss-repo-conf-url` is not "Foo bar baz" but an old value.
<img width="512" alt="screen shot 2015-12-09 at 10 22 18" src="https://cloud.githubusercontent.com/assets/353767/11684516/74230bba-9e72-11e5-89fe-d3716c645bd1.png">

Not sure if this is relevant or not - I was editing as `konstan` the component owned by `sixsq_dev`.

**Comment by rbf** [comment]
Is that twice the same screenshot or I don't see the differences? :flushed: 

I think that the server only takes into account modifications of the default value of a parameter for existing parameters. It's the same reason that the `Input`/`Output` direction cannot be changed either for existing parameters (and therefore we disabled its edition from the UI).

@schaubl Do you confirm my supposition?

**Comment by konstan** [comment]
Oops sorry :) I'll update the screenshot in 30 min.

**Comment by konstan** [comment]
@rbf I've updated the second screenshot.

**Comment by rbf** [comment]
Thanks, @konstan :+1: 

My point is still open though:

> I think that the server only takes into account modifications of the default value of a parameter for existing parameters. It's the same reason that the Input/Output direction cannot be changed either for existing parameters (and therefore we disabled its edition from the UI).
> 
> @schaubl Do you confirm my supposition?

**Comment by schaubl** [comment]
> @schaubl Do you confirm my supposition?

Yes, I checked the code and only the value is taken into account if the parameter already exist.
See https://github.com/slipstream/SlipStreamServer/blob/v2.20-community/jar-service/src/main/java/com/sixsq/slipstream/user/FormProcessor.java#L126

**Comment by konstan** [comment]
@schaubl Thanks.  I think we need to let the user to update the description as well.  And as it looks like this is a server side code - I'm creating the corresponding issue on SSServer.

**Comment by konstan** [comment]
Tracked in https://github.com/slipstream/SlipStreamServer/issues/587
