### ISSUE TITLE
I can set "Max provisioning failures" only the first component

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#531]
![screen shot 2016-01-25 at 10 15 39](https://cloud.githubusercontent.com/assets/2462866/12546874/149f3e7a-c34d-11e5-9fd8-650abf572851.png)

**Comment by rbf** [comment]
@schaubl have you tried to scroll down the element? :/

**Comment by schaubl** [comment]
> @schaubl have you tried to scroll down the element? :/ 

@rbf: Yes

**Comment by schaubl** [comment]
I don't know why but now it works.

**Comment by mebster** [comment]
Can we close this then?

**Comment by rbf** [comment]
Yes for me. @schaubl ?

**Comment by schaubl** [comment]
Ok. We will see if it appear again.
