### ISSUE TITLE
Display a password placeholder on the profile page in `view` mode, to hint the user that the password can be edited in the profile page.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#540]
As of now, there is no visual cue that the SlipStream password can be changed in the user profile page, so that the user does not know how to change the password.

![screen shot 2016-02-16 at 18 09 49](https://cloud.githubusercontent.com/assets/807084/13084164/7e4bf858-d4d8-11e5-9bf7-040f54c279be.png)

**Comment by loomis** [comment]
Won't be implemented.
