### ISSUE TITLE
Enhance the usage gauges in the dashboard to make the information more relevant and less confusing

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#542]
- ~~Add a sentence above each cloud gauge to say `X apps [in that cloud]`. Clicking in that sentence will show the **Deployments** tab filtered for the corresponding cloud.~~
  => The number of deployed apps was added like the other values, under an icon. (see implementation screenshot in [the comment below](https://github.com/slipstream/SlipStreamUI/issues/542#issuecomment-197427160)).

- [x] Make clear that the number within the gauges mean VMs (maybe with a tooltip). Clicking in the gauge will show the **VMs** tab filtered for the corresponding cloud. (Currently if shows the Deployment tab).

- [x] The number within the gauge should exactly match the number of each type of rows in the VM table, e.g. 1/1/1 as in the following screenshot:

![screen shot 2016-02-08 at 15 59 14](https://cloud.githubusercontent.com/assets/807084/13117922/2d42185a-d5a2-11e5-8c05-1fc73e32db03.png)

- [x] Display detailed separation below the gauge (with different texts) for own VMs (i.e. was started by the logged-in user from SlipStream) and the 6 cases we identified as unexpected (mostly `unknown`) VMs (i.e. which `describe-instance` of the current logged-in user sees but were not directly started by her on SlipStream):

  * VM is `unknown` because it was started by the currently logged-in user but outside the current SlipStream instance (e.g. directly in the cloud infrastructure)

  * VM is known by SlipStream but the run is not accessible (i.e. on the UI, not clickable) by the currently logged-in user because it was started by another SlipStream user but the logged-in user shares credentials with this other user

  * VM is `unknown` because it was started by another user outside the current SlipStream instance but the logged-in user shares credentials with this other user

  * VM is known by SlipStream but the run is not accessible (i.e. on the UI, not clickable) by the currently logged-in user because it was started by another SlipStream user with her own credentials, but the cloud shares resources among a group of users to which the logged-in user also belongs

  * VM is `unknown` because it was started by another user with her own credentials outside the current SlipStream instance, but the cloud shares resources among a group of users to which the logged- in user also belongs

  * VM is `unknown` because of SlipStream still deploying the VM (this case should appear as identified by SlipStream in short

- [x] Merge https://github.com/slipstream/SlipStreamServer/pull/646 once this task is done

**Comment by rbf** [comment]
@mebster @schaubl 
In this issue we want to bring more details from the `Deployments` and `VMs` tables into the dashboard gauges. There is something to sort out though: in the dashboard metadata we only have following info about the `usage`:

```xml
<usage class="java.util.ArrayList">
    <usageElement cloud="Cloud1" quota="20" currentUsage="0"/>
    <usageElement cloud="Cloud2" quota="20" currentUsage="8"/>
    <usageElement cloud="Cloud3" quota="20" currentUsage="1"/>
    <usageElement cloud="Cloud4" quota="20" currentUsage="3"/>
</usage>
```

The rest of the suggested additional pieces of information like the number of running apps per cloud and the detailed number of unknown VMs are not known in the dashboard metadata (see: https://nuv.la/dashboard?media=xml).

We can:

1. Change the server to include this information into the dashboard metadata (and e.g. removing the runs info at the same time: https://github.com/slipstream/SlipStreamServer/issues/636)

1. Let the client update the gauge for the selected cloud when it's selected, gathering the information from the corresponding tables.

If the request to include this info in the server is not very expensive, solution `1.` would be IMO preferable because it would let the user know in advance if and where are some issues.

What do you prefer?

**Comment by rbf** [comment]
As agreed with @schaubl and @mebster we need following task on the server to allow the current task: https://github.com/slipstream/SlipStreamServer/issues/642

**Comment by schaubl** [comment]
:warning:  Merge https://github.com/slipstream/SlipStreamServer/pull/646 once this task is done

**Comment by rbf** [comment]
Implementation:

![screen shot 2016-03-16 at 13 50 21 copy](https://cloud.githubusercontent.com/assets/807084/13821333/64b94eb0-eba1-11e5-9904-3fb23e38359d.png)

**Comment by schaubl** [comment]
There is the following issue: The colors of the new fields are updated only we we do a full reload of the page.
