### ISSUE TITLE
Add a big + after the dashboard gauges as a link to the editable user profile to help the user to configure another cloud.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#563]
As [suggested](https://sixsq.slack.com/archives/ux/p1458313519000064) by @mebster.

Mockup:

![screen shot 2016-03-16 at 13 50 21 mockup](https://cloud.githubusercontent.com/assets/807084/13956741/2e633cc4-f04a-11e5-8d46-a554a82254da.png)

**Comment by sixsq-hudson** [comment]
"Add a new cloud (or new region)"

**Comment by rbf** [comment]
Current implementation:

![screen shot 2016-04-13 at 11 33 15](https://cloud.githubusercontent.com/assets/807084/14489068/8d533e14-016b-11e6-82a4-374d0f09904a.png)
