### ISSUE TITLE
Cannot define tags from the "Build" dialog

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#565]

**Comment by rbf** [comment]
This is not a bug, but an enhancement. Do we want to implement tags also for builds? Flagging it as `✖︎ Outdated - Flagged for deletion` for discussion.

**Comment by rbf** [comment]
Discussed with @loomis. There is no need for builds to have tags, since it's rather a one-shot action, and the run does not stay after the build is terminated. Closing issue.
