### ISSUE TITLE
Make action buttons dynamic for mobile devices

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#568]
The action buttons stack on a mobile, making the selection awkward

**Comment by rbf** [comment]
This issue refers to the actions in the secondary menu, and it's still valid:

![screen shot 2016-04-14 at 18 02 06](https://cloud.githubusercontent.com/assets/807084/14534818/20580e88-026b-11e6-9345-5b2fed33b4ab.png)

**Comment by cjdcordeiro** [comment]
this includes the footer overlapping other elements as well:
