### ISSUE TITLE
For a regular user /dashboard shows gauges for all the configured clouds on the instance

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#573]
Instead it should show only the ones that are configured in the user's profile.  This is a regression in v3.1.

**Comment by konstan** [comment]
<img width="1182" alt="screen shot 2016-04-06 at 13 42 54" src="https://cloud.githubusercontent.com/assets/353767/14316011/dc3c75b0-fc00-11e5-9947-423404638b5a.png">

**Comment by rbf** [comment]
Indeed, this is a regression.

Here are some relevant code lines to look at when working on this issue:

- https://github.com/slipstream/SlipStreamUI/blob/v3.1-community/clj/src/slipstream/ui/models/dashboard.clj#L16-L21

- https://github.com/slipstream/SlipStreamUI/blob/v3.1-community/clj/src/slipstream/ui/models/dashboard.clj#L21

- https://github.com/slipstream/SlipStreamUI/blob/v3.1-community/clj/test/slipstream/ui/models/dashboard_test.clj

- https://github.com/slipstream/SlipStreamUI/blob/v3.1-community/clj/src/slipstream/ui/views/user.clj#L87

- https://github.com/slipstream/SlipStreamUI/blob/v3.1-community/clj/src/slipstream/ui/util/current_user.clj#L99

**Comment by rbf** [comment]
@loomis: This can be easily hot-fixed, if need be: you have merely to add the keyword `:vm-quota` after the keyword `:cloud` [here](https://github.com/slipstream/SlipStreamUI/blob/v3.1-community/clj/src/slipstream/ui/models/dashboard.clj#L21).

**Comment by rbf** [comment]
@loomis: To fully hot-fix this regression, please modify the file `clj/src/slipstream/ui/models/dashboard.clj` as per [this commit](https://github.com/slipstream/SlipStreamUI/commit/0718bb0baaa07ce3ad7a77b3a1313fca602d294f#diff-88379d279236a532fc9555bf1ffdadd8).
