### ISSUE TITLE
Tour step "28. Usage gauge" does correctly point the targeted gauge but does not properly highlight it.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#574]
The gauges are now contained in a [`div.ss-usage-gauge-container`](https://github.com/slipstream/SlipStreamUI/blob/0718bb0baaa07ce3ad7a77b3a1313fca602d294f/clj/src/slipstream/ui/views/dashboard.clj#L39) (because of the detailed counters), while the selector for the tour step for the gauge targets the [`div#ss-usage-gauge-<cloud_name>`](https://github.com/slipstream/SlipStreamUI/blob/master/clj/src/slipstream/ui/tour/alice.clj#L196) element within. As a result, the `div` selected by the tour step is neither highlighted (i.e. popped up from the greyed-out background) nor clickable:

![screen shot 2016-04-07 at 14 21 27](https://cloud.githubusercontent.com/assets/807084/14350968/da438e84-fccc-11e5-8a53-7c94834c58c8.png)

This is IMO not a show-stopper, since the tour can be finished without problems.

**Comment by konstan** [comment]
Connected to https://github.com/SixSq/tasklist/issues/1012
