### ISSUE TITLE
SSH problems with the orchestrator should be shown to the user

### ISSUE THREAD

**Issue by sw-irou** [slipstream/SlipStreamUI#58]
When there are problems with the orchestrator template or the server configuration such that a deployment will never complete, due to errors like the following in the server's log, it would be helpful if the server returned an error message.

Currently it simply sits with the orchestrator in state 'ON', but 'Inactive'.

These were all using the Abiquo connector.

The errors are as follows, with details of how they can be recreated:
1. No authentication methods available (e.g. public key only, but server is only trying password):
org.jclouds.rest.AuthorizationException: (root:pw[abcdef1234567890]@192.0.2.1:22) (root:pw[abcdef1234567890]@192.0.2.1:22) error acquiring {hostAndPort=192.0.2.1:22, loginUser=root, ssh=null, connectTimeout=60000, sessionTimeout=60000} (not retryable): Exhausted available authentication methods

In our case this occurred when password authentication was disabled, but the server's root SSH key had been placed on the orchestrator template- though it refused to use it.
To recreate error (should be guaranteed even if our issue is a configuration problem): Disallow password and public key authentication on the orchestrator template.

2. SSH password not set (it would be good if it would then try the public key instead of complaining):
com.sixsq.slipstream.exceptions.ConfigurationException: missing configuration property: interoute.orchestrator.ssh.password

To recreate: Add a new Abiquo connector, but configure it without a password.

**Comment by rbf** [comment]
Discussed with @loomis. This issue is outdated. Closing issue.
