### ISSUE TITLE
Use /auth/login instead of /login

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#590]
:warning: the parameter `username` become `user-name`

**Comment by loomis** [comment]
Migrate to using the clojure side authentication rather than the redirected resources on the Java side.

**Comment by st** [comment]
- [ ] Check no other client depend on `/login`.
- [ ] remove `/login` for POST
- [ ] Use `/auth/login` instead of `/login` only for POST.
- [x] rename username to user-name : no longer needed

**Comment by schaubl** [comment]
Still relevant
