### ISSUE TITLE
As a User, I can see on dashboard alerts on failures or timeouts to get cloud state of VMs

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#591]
The initial issue is that on "slow" clouds (>60 sec to list VMs) dashboard doesn't warn about failures to get VMs state from cloud. 

This is probably an epic that touches client/server and UI.

**Comment by loomis** [comment]
To be done after Riemann is in place to collect and act on these failures.  This also needs another ticket on the SlipStreamServer side to complete this feature.
