### ISSUE TITLE
Add a hint when component inherits a script or a parameter from it's ancestor components.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#592]
When a component inherits a parameter from a parent, the parameter does not appear on the `Application Parameters` section, but it's only seen on the "Deploy..." dialog. A similar thing happens with the scripts: they do not appear in the `Application Workflows` of the child component, but they do get executed as expected.

Maybe we could add a textual hint in the `Application Parameters` or `Application Workflows` sections to let the user know what will happen on deploy.

**Comment by mebster** [comment]
This sounds like a hack.  Why not fixing the UI and indicate that the parameter or target is inherited?

**Comment by rbf** [comment]
Because the inherited parameter or target is not displayed in the child module.
