### ISSUE TITLE
Trying to remove a parameter while creating another with the same name ignores the operation

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#595]
This is confusing and compounds the frustration from having the remove a parameter to change the description

**Comment by konstan** [comment]
@0xbase12 What is the state of this issue?  It's in "ready to validate", but I see not PRs associated with it.  Thanks.

**Comment by 0xbase12** [comment]
This was fixed and merged in this issue slipstream/SlipStreamServer#886. You can close it
