### ISSUE TITLE
Debug mode of the deployment would be useful

### ISSUE THREAD

**Issue by yazun** [slipstream/SlipStreamUI#6]
Which would have additional features:
- placeholder for recipe to 'clean machine'
- continuously running orchestrator
- button to restart machine (reboot without re-deployment, but with executing 'clean machine' recipe)
- easier access to logs (real-time, in the UI console preferably)
- pulling changes from the deployment recipes from the nodes back to the UI

**Comment by rbf** [comment]
@loomis @mebster Any comments on this issue? Do you want to still consider this feedback, or is it not relevant anymore?

**Comment by rbf** [comment]
Discussed with @loomis. This issue is outdated. Too generic enhancement. Some things have been partially implemented. Closing issue.
