### ISSUE TITLE
In dashboard, add timestamps in Nuvlabox connector states for the last state change.

### ISSUE THREAD

**Issue by rbf** [slipstream/SlipStreamUI#608]
The goal is to see `Offline - Last seen on <timestamp>` and `Online - since <timestamp>`.

@mebster: Do you validate both cases?
@st: Could we add always a timestamp for the last state change next to the `state` value in the `service-offer` response?

**Comment by mebster** [comment]
Yes for offline, I'm not sure the timestamp is required for online.

**Comment by st** [comment]
I agree with @mebster , we should only indicate`Offline - Last seen on <ts>`
