### ISSUE TITLE
make support link more prominent

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#610]
Make the support link in SlipStream more prominent.

 - [x] Rename "Contact Us" to "Support"
 - [x] Make it a top-level menu item.
 - [x] Should appear only if a non-empty value is set for support email parameter.
 - [ ] Default value for the support email parameter should be empty.

**Comment by rbf** [comment]
@loomis How you'd like the `support email parameter` to be saved?

**Comment by loomis** [comment]
There is an existing parameter for this in the SlipStream support section.  The text is "Email address for SlipStream support requests”.

**Comment by rbf** [comment]
✅ Done. See #slipstream channel for demo.

> Default value for the support email parameter should be empty.

@loomis Where should this be changed?

**Comment by loomis** [comment]
I've fixed a misnamed namespace and added/updated kibit/eastwood to configuration.
