### ISSUE TITLE
favorite applications

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#622]
As a SlipStream user, I can mark application components or applications as "favorites". Those favorites then show up in my rendering of the App Store. This avoids having to dig through the workspace hierarchy to run/edit those application components or applications that I use frequently.

**Comment by rbf** [comment]
A first implementation of a favorites mechanism could be pretty straight forward, like something in the lines of following mockup:

![20160621_slipstream_appstore_favorites](https://cloud.githubusercontent.com/assets/807084/16237387/859536ee-37dc-11e6-972f-9f6fffb686c9.png)

**Comment by schaubl** [comment]
👍 . I think user's favorites should always be on the top

**Comment by rbf** [comment]
The order has to be consistent regardless of the favorite flag. Otherwise a user would not be able to quickly fav/de-fav an app because it would be relocated after the first click.
If a user wants to quickly see all their favorite apps, the proposed top filter is a more efficient solution.

**Comment by loomis** [comment]
Won't be implemented.  May come back in new web interface.
