### ISSUE TITLE
A nonexistent node is deplayed in the graphical deployment overview

### ISSUE THREAD

**Issue by 0xbase12** [slipstream/SlipStreamUI#643]
graphical bug, two machines labeled "slave" in my recipe but three are displayed, and one is named "slave.21".

http://support.sixsq.com/helpdesk/tickets/1140
<img width="690" alt="screen shot 2016-07-18 at 10 55 31" src="https://cloud.githubusercontent.com/assets/5518233/16909983/399539c4-4cd6-11e6-96fc-fd837f5d02e2.png">

**Comment by bryan-brancotte** [comment]
Other example of this bug
![image](https://cloud.githubusercontent.com/assets/11556772/16947151/a09d967a-4dad-11e6-8697-fa9165d89d7d.png)
