### ISSUE TITLE
Input field not wide enough with long component and parameter names

### ISSUE THREAD

**Issue by bryan-brancotte** [slipstream/SlipStreamUI#645]
Graphical problem encountered on chrome 50.0.2661.94, from what i see it's a bootstrap issue, using [modal-lg](http://getbootstrap.com/javascript/#modals-sizes) solves it.

![without](https://cloud.githubusercontent.com/assets/11556772/16921778/325fb066-4d13-11e6-869f-8cbb1f9ee185.png)
![with](https://cloud.githubusercontent.com/assets/11556772/16921682/c55aaa16-4d12-11e6-8b1a-132e68805689.png)

**Comment by isartcanyameres** [comment]
Same issue in firefox
![badlayout](https://cloud.githubusercontent.com/assets/1107866/17023296/f65b268a-4f52-11e6-9701-b0a5c28dc483.png)
