### ISSUE TITLE
Improve modification of application's component

### ISSUE THREAD

**Issue by elouanKeryell-Even** [slipstream/SlipStreamUI#647]
Sometimes I want to modify an application by changing the components it points onto.

For now, when editing an application, I have to remove the said component reference and to recreate it. However, I have to keep the same component name so that I don't have to change our calls to `ss-get component_name:multiplicity` & `ss-get component_name:hostname` in the Deployment scripts. And deleting a component and recreating a new one with the same name doesn't work (fails with `Enter a unique node name.`, see screenshot below).

![unique_name_issue_with_annotations](https://cloud.githubusercontent.com/assets/9483289/16948799/03fe0714-4db7-11e6-8340-4eb212b21839.PNG)

Currently this has to be done in 2 steps:
- Edit application; Remove component; Save
- Edit application; Recreate component; Save

I think a nice way to improve this would be to be able to directly modify the component field when editing the application (see screenshot below).

![with_annotation](https://cloud.githubusercontent.com/assets/9483289/16948503/5a1cad3c-4db5-11e6-9297-0ed4a97916da.png)

Obviously this is a low priority issue :)

**Comment by 0xbase12** [comment]
If you have an application with 2 components. 
We remove a parameter from component 1.
When we edit the application and want to save it again, an error message say that removed parameter doesn't exit in component 1.
To fix it, the user have to manually delete the component and mappings with this component 1 and add it again to get the component without the parameter newly removed from comp1.

There is also the naming issue (can't recreate the component with the same name)

**Comment by 0xbase12** [comment]
- [x] Not unique name issue
- [ ] Heritage component issue

**Comment by 0xbase12** [comment]
Not able to change the default Cloud of a component in Application Components mappings.

To reproduce:
1) edit an application
2) change the default cloud to a specific cloud
3) save
4) inspect Application components: Field Default cloud for the component still on default cloud

**Comment by konstan** [comment]
@0xbase12 Can this issue be closed?  I see PRs are merged.

**Comment by 0xbase12** [comment]
Yes it can be closed

**Comment by elouanKeryell-Even** [comment]
I confirm the issue is fixed on [nuv.la](https://nuv.la).
