### ISSUE TITLE
2.0.5- Parameter category would benefit from help button

### ISSUE THREAD

**Issue by sw-irou** [slipstream/SlipStreamUI#66]
In 2.0.5 the parameter category field on deployment can take one of two options (Input/Output). While one can dig out what they mean from the docs, it would be nice to have one of the help popup '?'s next to them to save a trip to the docs.

**Comment by rbf** [comment]
Still relevant. Promoting to `S05 Ready to work`.

**Comment by rbf** [comment]
IMO this point is today still relevant.

![screen shot 2016-04-14 at 16 29 40](https://cloud.githubusercontent.com/assets/807084/14531560/22e8663c-025e-11e6-96d0-3f290b031a4e.png)
