### ISSUE TITLE
Usage page shows too narrow 3rd column

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#677]

**Comment by konstan** [comment]
Connected to https://github.com/SixSq/tasklist/issues/1012

**Comment by konstan** [comment]
And it contains no description about the reported numbers.  This is the old rendering http://ssdocs.sixsq.com/en/latest/_images/usage.png

**Comment by mebster** [comment]
This is a problem since we can't match the metric the value corresponds to.
