### ISSUE TITLE
dashboard should display total quota for configured clouds only

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#694]
Here is what users report with v3.18

![rzbok9ybvwvgss5ytifq0a-6cvkarhycia](https://cloud.githubusercontent.com/assets/353767/21314546/f6a02c8c-c5f7-11e6-941c-9c418c461f2c.png)

Reference http://support.sixsq.com/helpdesk/tickets/1288

**Comment by mebster** [comment]
Looked to https://github.com/SixSq/tasklist/issues/1292
