### ISSUE TITLE
In the user profile, set "Cloud usage email" to daily as default

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#715]
From @mebster `It contains instructions on how to switch it off. This way users learn about this feature in a natural way.`

Connected to https://github.com/SixSq/tasklist/issues/1012

**Comment by cjdcordeiro** [comment]
would it be reasonable to also have a weekly (and even monthly) option? After all one of the main advantages of this usage report is to be able to crosscheck with the providers invoice, and those usually arrive on a monthly basis
