### ISSUE TITLE
When user has a long name UI blocks overlay messages

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamUI#729]
Example where the error message is hidden behind the long name and the user is not able to see it.
![pbmessage](https://cloud.githubusercontent.com/assets/353767/26205909/80d23ca4-3be3-11e7-80e5-3ba4adc10537.png)

**Comment by loomis** [comment]
This will be a common situation as more people (mainly HNSciCloud) will be using the federated identity to create accounts on Nuvla. The identifiers used are typically hundreds of characters long. Initially fix this for the user header.  Other changes will have to be made (later) throughout the UI.
