### ISSUE TITLE
Get the possible values ​​of a parameter from the cloud

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#74]
For example if a user has an OpenStack account configured and he want to create a new SlipStream Image, the possibles imagesID could be retrieved from the Cloud and the same applies to InstancesTypes, SecurityGroups, ...

This can be implemented with auto-completion on a text field or with a dropdown menu.
With auto-completion the user can bypass the list returned by the Cloud (for example if the Cloud don't implement this feature)
While a dropdown menu can enforce the user to use valid values.

**Comment by rbf** [comment]
IMO this point is today still relevant.

**Comment by schaubl** [comment]
Still relevant.
Adding Epic label because it will require a update of the "base architecture" of SlipStream.
