### ISSUE TITLE
Cloud configurations not populated when choosing parent machine image

### ISSUE THREAD

**Issue by sw-irou** [slipstream/SlipStreamUI#75]
When choosing a parent machine image for a new machine image, the 'Cloud Configurations' tab does not immediately populate its values.

After saving, the values appear populated, but prior to that point they are left empty.

To recreate (assuming a suitable parent image with cloud configuration exists):
1. New Machine Image
2. Fill in name and description
3. Go to Cloud Image Identifiers and Image Hierarchy tab.
4. Select parent image.
5. Go to Cloud Configuration tab.
6. Confirm that expected configuration is not present.
7. Save image.
8. Reopen saved image.
9. Go to Cloud Configuration tab.
10. Confirm that expected configuration is present.

**Comment by rbf** [comment]
This is still valid today.
