### ISSUE TITLE
dashboard for running VMs shows every machine twice

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#76]
The dashboard currently shows all VMs for a user twice in the VM section.  This is true whether they are VMs started by SS or not.

**Comment by mebster** [comment]
This issue is similar to the concurrent issue reported for large deployments by CERN.

**Comment by rbf** [comment]
@mebster 
I'm not able to reproduce this bug. Is it still relevant?
Please close this issue if not.

**Comment by mebster** [comment]
@loomis ?

**Comment by schaubl** [comment]
It's probably not an issue of the UI.

**Comment by loomis** [comment]
Haven't noticed this on recent versions.  Closing for now.
