### ISSUE TITLE
build button should be inactive for base images

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#77]
The build button should be deactivated for base images, since they cannot be built.

**Comment by rbf** [comment]
Still relevant. Promoting to `S05 Ready to work`.

**Comment by rbf** [comment]
Please validate also the `disabled-reason` message:

![screen shot 2015-03-30 at 18 12 49](https://cloud.githubusercontent.com/assets/807084/6900734/d35b41b0-d708-11e4-90de-dd76e10aaa18.png)

NB: All actions in this secondary menu that are disabled display a warning with a `disabled-reason` message on click, but they do not perform any other action, nor they are highlighted on mouseover, like the active actions do.
