### ISSUE TITLE
dashboard display of run ids should be consistent between sections

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamUI#78]
In the "Deployments/Builds/Runs" section, the run identifier is listed as "Run ID" and abbreviated to the first 8 characters.  In the "Running Virtual Machines" section, the run identifier is listed as "SlipStream ID" and the full value is given.   The display should be consistent between the two sections, preferably adopting the style of the "Deployments..." section.

**Comment by rbf** [comment]
Still relevant. In the new UI (version > 2.4) both cases display the run identifier abbreviated to the first 8 characters, but naming inconsistency still applies.

Promoting to `S05 Ready to work`.

**Comment by schaubl** [comment]
@rbf: Can we close this issue ?

**Comment by rbf** [comment]
Indeed:

![screen shot 2015-03-17 at 09 06 23](https://cloud.githubusercontent.com/assets/807084/6683357/67793aca-cc85-11e4-8486-c4d2a0dfccbf.png)

![screen shot 2015-03-17 at 09 06 45](https://cloud.githubusercontent.com/assets/807084/6683358/6779a988-cc85-11e4-91f6-1bc463b06e53.png)

Closing issue.
