### ISSUE TITLE
login buttons are not fully responsive

### ISSUE THREAD

**Issue by cjdcordeiro** [slipstream/SlipStreamUI#788]
there seems to be a min-width for the HN and SixSq fed login buttons.

replicate it by decreasing the window's width dramatically

**Comment by loomis** [comment]
@cjdcordeiro These have completely changed for v3.55.  Can you try with the WebUI code on master to see if you have the same problem?

**Comment by loomis** [comment]
With v3.55, the layout of the login buttons is completely different. 

Browser at minimum width:
<img width="200" alt="browser-minimum-width" src="https://user-images.githubusercontent.com/490506/42673506-12f18d0a-866c-11e8-9375-fadc195d68da.png">

iPhone in portrait orientation:
<img width="275" alt="iphone-portrait" src="https://user-images.githubusercontent.com/490506/42673525-2d16e4aa-866c-11e8-9dbc-0832686109ce.png">

iPhone in lanscape orientation:
<img width="372" alt="iphone-landscape" src="https://user-images.githubusercontent.com/490506/42673529-36555132-866c-11e8-975d-8015dd1f249e.png">

**Comment by loomis** [comment]
See slipstream/SlipStreamWebUI#166 for more details.
