### ISSUE TITLE
If the "save message" contains new lines they are removed

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#82]
Up to 3 new lines should be kept on the "header" part of the page.
New lines should be replaced by a space in the version view.

**Comment by rbf** [comment]
New UI (version > 2.4) replaces `newlines` in save messages with spaces:

![multiline_commit_message](https://cloud.githubusercontent.com/assets/807084/6216916/9ee43376-b60e-11e4-97a8-f04e4b70dac0.png)

For me this behaviour is correct.

@schaubl 
Do you agree closing this issue?

**Comment by schaubl** [comment]
@rbf : Yes
