### ISSUE TITLE
On the user page the title of the Summary section should not be Summary.

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#83]
It could be one of the following:
- User
- User Informations
- User Details
- ...

**Comment by rbf** [comment]
I find this is a valid point.

**Comment by schaubl** [comment]
I'm increasing this issue to 3 stars because it's very simple to implement.

@mebster and/or @loomis can you consider this issue for the next sprint ?

**Comment by rbf** [comment]
Promoting to `Shortlisted for Sprint` since still valid and quick to implement.
