### ISSUE TITLE
On the user page the General section should always be the second section.

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamUI#84]
Currently the first section is always Summary and others sections are sorted by the name of the cloud connector instance.

**Comment by rbf** [comment]
Still relevant. Promoting to `S05 Ready to work`.

**Comment by schaubl** [comment]
I'm increasing this issue to 3 stars because it's very simple to implement.

@mebster and/or @loomis can you consider this issue for the next sprint ?

**Comment by rbf** [comment]
Moving to `Ready to Validate`.

I also added icons for each section to help differentiating the content (in the same way that we began doing for the run page):

![screen shot 2015-03-30 at 15 00 42](https://cloud.githubusercontent.com/assets/807084/6896632/b105f670-d6ed-11e4-8ddd-ecdee69651e5.png)

Please comment if you disagree.
Cheers.

**Comment by schaubl** [comment]
:+1:
