### ISSUE TITLE
Add log of the different deployment/build/run events

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamUI#88]
This should include the date for each event - e.g.:
- State transition
- Termination (manual)
- First abort call (with reason)

**Comment by rbf** [comment]
@mebster 
This is not clear for me. Where is the log to be added? In which form?
IMO this is not ready for sprint yet.
Moving back to `S00 Backlog`.

**Comment by mebster** [comment]
This should be first done on the server side (https://github.com/slipstream/SlipStreamServer/issues/249)

**Comment by rbf** [comment]
This was implemented a while ago and it's in production:

![screen shot 2016-04-14 at 16 44 08](https://cloud.githubusercontent.com/assets/807084/14532095/26cd30be-0260-11e6-81b8-8f3ee7e63f38.png)

Closing the issue.
